<html>
<head>
<title>UgDimDisplayRounded.c</title>
</head>
<body bgcolor="#ffffff">
<pre><a name="anchor-0"></a>
/*
	Copyright (c) 2024 PTC Inc. and/or Its Subsidiary Companies. All Rights Reserved.
*/

<a name="anchor-1"></a>
/*------------------------------------------------------------------*\
Pro/Toolkit includes
\*------------------------------------------------------------------*/
#include &lt;ProToolkit.h>
<a name="anchor-2"></a>#include &lt;ProObjects.h>
#include &lt;ProFeature.h>
#include &lt;ProDimension.h>
#include &lt;ProSolid.h>
#include &lt;ProUtil.h>
<a name="anchor-3"></a>#include &lt;ProMessage.h>
#include &lt;PTApplsUnicodeUtils.h>
/*------------------------------------------------------------------*\
Application includes 
\*------------------------------------------------------------------*/
<a name="anchor-4"></a>#include &lt;TestError.h>

/*==================================================================*\
FUNCTION : UserDimDisplayRounded()
PURPOSE  : Change the displayed value of a selected model dimension to 
<a name="anchor-5"></a>	   rounded/non-rounded.
	   
\*==================================================================*/
ProError UserDimDisplayRounded()
{
<a name="anchor-6"></a>    ProMdl model ;               /* current model */
    ProSelection *p_sel_feat ;   /* selected feature */
    ProSelection *p_sel_dim ;    /* selected dimension */
    ProModelitem dim_mdlitem ;   /* dimension Modelitem */
    int n_sel_feat = -1 ;             /* no. of selected features */
<a name="anchor-7"></a>    int n_sel_dim = -1;              /* no. of selected dims */
    ProFileName msg_file ;       /* message file */
    int err ;                    /* return status */
    double value;                /* dimension value */
    double newdimval ;           /* user-entered dim value */
<a name="anchor-8"></a>    ProCharLine str1 ;           /* message string */
    ProBoolean display_rounded;  /* rounded display status */

    ProStringToWstring(msg_file, &quot;msg_ugfund.txt&quot;) ;

<a name="anchor-9"></a>/*------------------------------------------------------------------*\
    Check for a model.
\*------------------------------------------------------------------*/
    err = ProMdlCurrentGet(&amp;model);
    ERROR_CHECK(&quot;UserDimDisplayRounded()&quot;, &quot;ProMdlCurrentGet()&quot;, err); 
<a name="anchor-10"></a>    if (err != PRO_TK_NO_ERROR)
    {
       ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, 
           &quot;Error getting current model.&quot;); 
       return(err) ; 
<a name="anchor-11"></a>    }

/*------------------------------------------------------------------*\
    Get a feature to modify.
\*------------------------------------------------------------------*/
<a name="anchor-12"></a>    ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, &quot;Select a feature.&quot;); 
           
    err = ProSelect(&quot;feature&quot;, 1, NULL, NULL, NULL, NULL, 
        &amp;p_sel_feat, &amp;n_sel_feat) ; 
    ERROR_CHECK(&quot;UserDimDisplayRounded()&quot;, &quot;ProSelect()&quot;, err); 
<a name="anchor-13"></a>    if ( err != PRO_TK_NO_ERROR || n_sel_feat &lt; 1)
    {
        ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, 
            &quot;Error or abort during selection.&quot;) ; 
        return(err) ; 
<a name="anchor-14"></a>    }

    ProSelectionUnhighlight (p_sel_feat [0]);

/*------------------------------------------------------------------*\
<a name="anchor-15"></a>    Show the dimensions on the feature.
\*------------------------------------------------------------------*/
    err = ProFeatureParamsDisplay (p_sel_feat [0], PRO_DIM_PARAM);
    ERROR_CHECK (&quot;UserDimDisplayRounded()&quot;, &quot;ProFeatureParamsDisplay()&quot;, err); 
 
<a name="anchor-16"></a>/*------------------------------------------------------------------*\
    Get the dimension to be changed.
\*------------------------------------------------------------------*/
    ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, &quot;Select a dimension.&quot;); 

<a name="anchor-17"></a>    err = ProSelect(&quot;dimension&quot;, 1, NULL, NULL, NULL, NULL, 
        &amp;p_sel_dim, &amp;n_sel_dim) ; 
    ERROR_CHECK(&quot;UserDimDisplayRounded()&quot;, &quot;ProSelect()&quot;, err); 
    if ( err != PRO_TK_NO_ERROR || n_sel_dim &lt; 1)
    {
<a name="anchor-18"></a>        ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, 
            &quot;Error or abort during selection.&quot;) ; 
        return(err) ; 
    }

<a name="anchor-19"></a>    err = ProSelectionModelitemGet(p_sel_dim[0], &amp;dim_mdlitem); 
    ERROR_CHECK(&quot;UserDimDisplayRounded()&quot;, &quot;ProSelectionModelitemGet()&quot;, 
        err); 

    err = ProDimensionIsDisplayRoundedValue(&amp;dim_mdlitem,
<a name="anchor-20"></a>			       &amp;display_rounded ); 
    ERROR_CHECK(&quot;UserDimDisplayRounded()&quot;, &quot;prodim_get_dimension()&quot;, err); 

/*------------------------------------------------------------------*\
    Change the dimension.
<a name="anchor-21"></a>\*------------------------------------------------------------------*/
    ProTKSprintf(str1, &quot;Toggling the Display Rounded property.&quot;) ; 
    ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, str1) ; 

    err = ProDimensionDisplayRoundedValueSet ( &amp;dim_mdlitem, !display_rounded); 
<a name="anchor-22"></a>    ERROR_CHECK(&quot;UserDimDisplayRounded()&quot;, &quot;ProDimensionValueSet()&quot;, err); 

    err = ProDimensionDisplayUpdate ( &amp;dim_mdlitem );

    ProMessageDisplay(msg_file, &quot;USER %0s F&quot;, 
<a name="anchor-23"></a>        &quot;Display Rounded property toggled.&quot;); 

    return(PRO_TK_NO_ERROR) ; 
}

<a name="anchor-24"></a>
</pre>
</body>
</html>
