<html>
<head>
<title>UgDrawingDimensions.c</title>
</head>
<body bgcolor="#ffffff">
<pre><a name="anchor-0"></a>
/*
	Copyright (c) 2024 PTC Inc. and/or Its Subsidiary Companies. All Rights Reserved.
*/

<a name="anchor-1"></a>#include &lt;ProToolkit.h>
#include &lt;ProDrawing.h>
#include &lt;ProDimension.h>
#include &lt;ProArray.h>
#include &lt;ProSolid.h>
<a name="anchor-2"></a>#include &lt;ProFeature.h>
#include &lt;ProPoint.h>
#include &lt;ProMessage.h>
#include &lt;ProAnnotation.h>
int UsrPointGeomitemsCollect(ProSolid solid, ProGeomitem **points);
<a name="anchor-3"></a>
/*====================================================================*\ 
FUNCTION: UsrDimPoints() 
PURPOSE  : Command to create a table of datum points 
\*====================================================================*/ 
<a name="anchor-4"></a>int UsrDimPoints() {
     ProError status;
     ProSelection *sel, csys_sel;
     int n_sel, n_points, p;
     ProSolid solid;
<a name="anchor-5"></a>     ProGeomitem csys_geom;
     ProAsmcomppath csys_comppath;
     ProMatrix trf;
     ProVector csys_pos, csys_3dpos, pnt_pos, dim_pos, outline[2];
     ProGeomitem *points;
<a name="anchor-6"></a>     ProDrawing drawing;
     ProSelection *attachments;
     ProDimSense *senses;
     ProDimension dimension, vbase_dim, hbase_dim;
     ProPoint point;
<a name="anchor-7"></a>     ProView view;
     ProFileName msgfil;

     ProStringToWstring (msgfil, &quot;msg_ugdrawing.txt&quot;);
    
<a name="anchor-8"></a>     ProMdlCurrentGet((ProMdl*)&amp;drawing);

/*--------------------------------------------------------------------*\ 
    Select a coordinate system. This defines the model (the top one
     in that view), and the common attachments for the dimensions 
<a name="anchor-9"></a>\*--------------------------------------------------------------------*/ 
     ProMessageDisplay(msgfil,&quot;USER Select csys&quot;);
     status = ProSelect(&quot;csys&quot;,1,NULL,NULL,NULL,NULL,&amp;sel,&amp;n_sel);
     if(status != PRO_TK_NO_ERROR || n_sel &lt; 1)
         return(0);
<a name="anchor-10"></a>
     ProSelectionCopy(sel[0], &amp;csys_sel);
     ProSelectionModelitemGet(csys_sel, &amp;csys_geom);
     ProSelectionAsmcomppathGet(csys_sel, &amp;csys_comppath);

<a name="anchor-11"></a>/*--------------------------------------------------------------------*\ 
    Get the root solid 
\*--------------------------------------------------------------------*/ 
     if(csys_comppath.table_num > 0)
         solid = csys_comppath.owner;
<a name="anchor-12"></a>
     else
         solid = csys_geom.owner;

/*--------------------------------------------------------------------*\ 
<a name="anchor-13"></a>    Get a list of datum points in the model 
\*--------------------------------------------------------------------*/ 
     UsrPointGeomitemsCollect(solid, &amp;points);
     ProArraySizeGet(points, &amp;n_points);
     if(n_points &lt; 1)
<a name="anchor-14"></a>         return(0);

/*--------------------------------------------------------------------*\ 
    Calculate where the csys is located on the drawing 
\*--------------------------------------------------------------------*/ 
<a name="anchor-15"></a>     ProSelectionPoint3dGet(csys_sel, csys_pos);
     if(csys_comppath.table_num > 0)
     {
         ProAsmcomppathTrfGet(&amp;csys_comppath, PRO_B_TRUE, trf);
         ProPntTrfEval(csys_pos, trf, csys_pos);
<a name="anchor-16"></a>     }

     memcpy(csys_3dpos, csys_pos, sizeof(ProVector));     
     ProSelectionViewGet(csys_sel, &amp;view);     
     ProDrawingViewTransformGet(drawing, view, PRO_B_TRUE, trf);     
<a name="anchor-17"></a>     ProPntTrfEval(csys_pos, trf, csys_pos);

/*--------------------------------------------------------------------*\ 
    Get the view outline 
\*--------------------------------------------------------------------*/ 
<a name="anchor-18"></a>     ProDrawingViewOutlineGet(drawing, view, outline);

/*--------------------------------------------------------------------*\ 
    Allocate the attachment arrays 
\*--------------------------------------------------------------------*/ 
<a name="anchor-19"></a>     ProArrayAlloc(2, sizeof(ProSelection), 1, (ProArray*)&amp;attachments);
     ProArrayAlloc(2, sizeof(ProDimSense), 1, (ProArray*)&amp;senses);

/*--------------------------------------------------------------------*\ 
    For each datum point... 
<a name="anchor-20"></a>\*--------------------------------------------------------------------*/ 
    for(p=0;p&lt;n_points;p++)
     { 
         ProDimAttachment* attachmentsArr = NULL;
/*--------------------------------------------------------------------*\ 
<a name="anchor-21"></a>        Calculate the position of the point on the drawing 
\*--------------------------------------------------------------------*/ 
         ProPointInit(points[p].owner, points[p].id, &amp;point);
         ProPointCoordGet(point, pnt_pos);
         ProPntTrfEval(pnt_pos, trf, pnt_pos);
<a name="anchor-22"></a>
/*--------------------------------------------------------------------*\ 
        Set up the &quot;sense&quot; information for the point attachment
         (Specify a vertical dimension) 
\*--------------------------------------------------------------------*/ 
<a name="anchor-23"></a>         senses[0].type = PRO_DIM_SNS_TYP_PNT;
         senses[0].sense = PRO_POINT_TYP_CENTER;
         senses[0].orient_hint = PRO_DIM_ORNT_VERT;

/*--------------------------------------------------------------------*\ 
<a name="anchor-24"></a>        Set up the &quot;sense&quot; information for the csys attachment 
\*--------------------------------------------------------------------*/ 
         senses[1].type = PRO_DIM_SNS_TYP_PNT;
         senses[1].sense = PRO_POINT_TYP_CENTER;
         senses[1].orient_hint = PRO_DIM_ORNT_NONE;
<a name="anchor-25"></a>
/*--------------------------------------------------------------------*\ 
        Set the attachment information 
\*--------------------------------------------------------------------*/ 
         ProSelectionAlloc(NULL, &amp;points[p], &amp;attachments[0]);
<a name="anchor-26"></a>         ProSelectionViewSet(view, &amp;attachments[0]);
         ProSelectionCopy(csys_sel, &amp;attachments[1]);


         ProArrayAlloc(2, sizeof(ProDimAttachment), 1, (ProArray*)&amp;attachmentsArr);
<a name="anchor-27"></a>         ProSelectionCopy(attachments[0], &amp;attachmentsArr[0][0]);
         ProSelectionCopy(attachments[1], &amp;attachmentsArr[1][0]);
         attachmentsArr[0][1] = NULL;
         attachmentsArr[1][1] = NULL;

<a name="anchor-28"></a>/*--------------------------------------------------------------------*\ 
        Calculate the dim position to be just to the left of the
         drawing view, midway between the point and csys 
\*--------------------------------------------------------------------*/ 
         dim_pos[0] = outline[0][0] - 20.0;
<a name="anchor-29"></a>         dim_pos[1] = (csys_pos[1] + pnt_pos[1]) / 2.0;
         dim_pos[2] = 0.0;

/*--------------------------------------------------------------------*\ 
        Create and display the dimension 
<a name="anchor-30"></a>\*--------------------------------------------------------------------*/ 
         ProDrawingDimensionCreate(drawing, attachmentsArr, senses, PRO_DIM_ORNT_NONE, dim_pos,
                         PRO_B_FALSE, &amp;dimension);

         ProAnnotationShow ((ProAnnotation*)&amp;dimension, NULL, view);
<a name="anchor-31"></a>
/*--------------------------------------------------------------------*\ 
        If this is the first vertical dim, create an ordinate base
        line from it, else just convert it to ordinate 
\*--------------------------------------------------------------------*/ 
<a name="anchor-32"></a>         if(p==0)
             ProDrawingOrdbaselineCreate(drawing, &amp;dimension,
                         csys_3dpos, &amp;vbase_dim);
         else
             ProDrawingDimToOrdinate(drawing, &amp;dimension, &amp;vbase_dim);
<a name="anchor-33"></a>
/*--------------------------------------------------------------------*\ 
        Set this dimension to be horizontal 
\*--------------------------------------------------------------------*/ 
         senses[0].orient_hint = PRO_DIM_ORNT_HORIZ;
<a name="anchor-34"></a>
/*--------------------------------------------------------------------*\ 
        Calculate the dim position to be just to the bottom of the
        drawing view, midway between the point and csys 
\*--------------------------------------------------------------------*/ 
<a name="anchor-35"></a>         dim_pos[0] = (csys_pos[0] + pnt_pos[0]) / 2.0;
         dim_pos[1] = outline[0][1] - 20.0;

/*--------------------------------------------------------------------*\ 
        Create and display the dimension 
<a name="anchor-36"></a>\*--------------------------------------------------------------------*/ 
         ProDrawingDimensionCreate(drawing, attachmentsArr, senses, PRO_DIM_ORNT_NONE, dim_pos,
             PRO_B_FALSE, &amp;dimension);

         ProAnnotationShow ((ProAnnotation*)&amp;dimension, NULL, view);
<a name="anchor-37"></a>
/*--------------------------------------------------------------------*\ 
        If this is the first horizontal dim, create an ordinate base line
         from it, else just convert it to ordinate 
\*--------------------------------------------------------------------*/ 
<a name="anchor-38"></a>         if(p==0)
             ProDrawingOrdbaselineCreate(drawing, &amp;dimension,
                         csys_3dpos, &amp;hbase_dim);

         else
<a name="anchor-39"></a>             ProDrawingDimToOrdinate(drawing, &amp;dimension, &amp;hbase_dim);

/*--------------------------------------------------------------------*\ 
        Free the attachment selection objects 
\*--------------------------------------------------------------------*/ 
<a name="anchor-40"></a>         ProSelectionFree(&amp;attachments[0]);
         ProSelectionFree(&amp;attachments[1]);
     }

    return(1);
<a name="anchor-41"></a> }

/*====================================================================*\ 
FUNCTION : UsrPointAddAction() 
PURPOSE  : Visit action function called for each datum point 
<a name="anchor-42"></a>\*====================================================================*/ 
ProError UsrPointAddAction(
     ProGeomitem *geomitem,
     ProError filt_status,
     ProAppData data) 
<a name="anchor-43"></a>{ 
/*--------------------------------------------------------------------*\ 
    Add the point to the array 
\*--------------------------------------------------------------------*/ 
    ProArrayObjectAdd((ProArray*)data, -1, 1, geomitem);
<a name="anchor-44"></a>    return(PRO_TK_NO_ERROR);
}

/*====================================================================*\ 
FUNCTION : UsrFeatureGetPointsAction() 
<a name="anchor-45"></a>PURPOSE: Visit action function called for each feature 
\*====================================================================*/ 
ProError UsrFeatureGetPointsAction(
     ProFeature *feature,
     ProError filt_status,
<a name="anchor-46"></a>     ProAppData data)
 {
     ProFeatStatus fstatus;

/*--------------------------------------------------------------------*\ 
<a name="anchor-47"></a>    If the feature is not active, skip it 
\*--------------------------------------------------------------------*/ 
     ProFeatureStatusGet(feature, &amp;fstatus);
     if(fstatus != PRO_FEAT_ACTIVE)
         return(PRO_TK_NO_ERROR);
<a name="anchor-48"></a>
/*--------------------------------------------------------------------*\ 
    Visit the datum points in the feature 
\*--------------------------------------------------------------------*/ 
     ProFeatureGeomitemVisit(feature, PRO_POINT, UsrPointAddAction, NULL,
<a name="anchor-49"></a>                              data);

     return(PRO_TK_NO_ERROR);
 }

<a name="anchor-50"></a>/*====================================================================*\ 
FUNCTION : UsrPointGeomitemsCollect() 
PURPOSE: Collect an array of datum points in the solid 
\*====================================================================*/ 
int UsrPointGeomitemsCollect(
<a name="anchor-51"></a>     ProSolid solid,
     ProGeomitem **points)
 { 
   /*--------------------------------------------------------------------*\ 
    Allocate the array 
<a name="anchor-52"></a>   \*--------------------------------------------------------------------*/ 
    ProArrayAlloc(0, sizeof(ProGeomitem), 1, (ProArray*)points);

   /*--------------------------------------------------------------------*\ 
    Visit the features 
<a name="anchor-53"></a>   \*--------------------------------------------------------------------*/ 
    ProSolidFeatVisit(solid, UsrFeatureGetPointsAction, NULL, points);
 }
</pre>
</body>
</html>
