<html>
<head>
<title>UgSketchedCurveCreate.c</title>
</head>
<body bgcolor="#ffffff">
<pre><a name="anchor-0"></a>
/*
	Copyright (c) 2024 PTC Inc. and/or Its Subsidiary Companies. All Rights Reserved.
*/

<a name="anchor-1"></a>

/*---------------------- Pro/Toolkit Includes ------------------------*/
#include &quot;ProToolkit.h&quot;
#include &quot;ProFeature.h&quot;
<a name="anchor-2"></a>#include &quot;ProElemId.h&quot;
#include &quot;ProExtrude.h&quot;
#include &quot;ProModFeat.h&quot;
#include &quot;ProStdSection.h&quot;
#include &quot;ProElement.h&quot;
<a name="anchor-3"></a>#include &quot;ProElempath.h&quot;
#include &quot;ProFeatType.h&quot;
#include &quot;ProFeatForm.h&quot;
#include &quot;ProSelection.h&quot;
#include &quot;ProSection.h&quot;
<a name="anchor-4"></a>#include &lt;PTApplsUnicodeUtils.h>

#include &quot;ProDtmCrv.h&quot;

static ProFileName message_file; 
<a name="anchor-5"></a>static FILE * log_file; 

#define C_LOG(a) ProTKPrintf (&quot;Status for %s is = %d\n&quot;, a, status ); \
	ERROR_CHECK( a, &quot;UgSktExtrusionCreate.c&quot;, status );

<a name="anchor-6"></a>#define C_PRINT(a) ProTKPrintf ( &quot;%s\n&quot;, a);

/*---------------------- Function Prototypes -------------------------*/
ProError ProDemoSketchedCurveCreate();

<a name="anchor-7"></a>/*------------------------- External Data ----------------------------*/
ProError ProDemoSectCreate();

/*------------------------- Global Data -----------------------------*/

<a name="anchor-8"></a>/*===============================================================*\
FUNCTION : ProDemoSketchedCurveCreate
PURPOSE  : Demonstrates the creation of the extruded protrusion
           base feature.
\*===============================================================*/
<a name="anchor-9"></a>ProError ProDemoSketchedCurveCreate()
{
  ProReference REPDEP_ref2;
  ProReference REPDEP_ref1;
  ProErrorlist            errors;
<a name="anchor-10"></a>  ProMdl                  model;
  ProModelitem            model_item;
  ProSelection            model_sel;
  ProFeature              feature;
  ProFeatureCreateOptions *opts = 0;
<a name="anchor-11"></a>  ProElempath             path;
  ProElempathItem         path_items[2];
  ProSection              section;
  ProAsmcomppath          comp_path;
  ProAsmcomppath          *p_comp_path = NULL;
<a name="anchor-12"></a>  ProValue                value;
  double                  width;
  double                  height;
  double                  bite_radius;
  double                  bite_height;
<a name="anchor-13"></a>  char                    name[PRO_NAME_SIZE];
  ProBoolean              alloc;

  ProElement sketch_element; 
  ProElement created_elemtree; 
<a name="anchor-14"></a>  
  ProElement pro_e_feature_tree;
  ProElement pro_e_feature_type;
  ProElement pro_e_curve_type;
  ProElement pro_e_std_section;
<a name="anchor-15"></a>  ProElement pro_e_std_sec_method;
  ProElement pro_e_std_sec_setup_plane;
  ProElement pro_e_std_sec_plane;
  ProElement pro_e_sketcher;
  ProElement pro_e_std_sec_plane_view_dir;
<a name="anchor-16"></a>  ProElement pro_e_std_sec_plane_orient_dir;
  ProElement pro_e_std_sec_plane_orient_ref;
  
  ProSelection *sketch_refs;

<a name="anchor-17"></a>  ProName 	wide_string;
  ProError 	status;
  ProValueData 	value_data;
  ProSelection * p_select;
  int 		n_select;
<a name="anchor-18"></a>  ProBoolean 	is_interactive = PRO_B_TRUE;
  
  ProStringToWstring ( message_file, &quot;utilities.txt&quot; ); 

  log_file = PTApplsUnicodeFopen ( &quot;ug_sketched_curve.log&quot;, &quot;w&quot; ); 
<a name="anchor-19"></a>  
  /*---------------------------------------------------------------*\
    Populating root element PRO_E_FEATURE_TREE 
  \*---------------------------------------------------------------*/
  C_PRINT( &quot; *** Processing Element PRO_E_FEATURE_TREE *** &quot; );
<a name="anchor-20"></a>  status = ProElementAlloc ( PRO_E_FEATURE_TREE, &amp;pro_e_feature_tree ); 
  C_LOG( &quot; ProElementAlloc &quot; );
  
  /*---------------------------------------------------------------*\
    Populating element PRO_E_FEATURE_TYPE 
<a name="anchor-21"></a>  \*---------------------------------------------------------------*/
  C_PRINT( &quot; *** Processing Element PRO_E_FEATURE_TYPE *** &quot; );
  status = ProElementAlloc ( PRO_E_FEATURE_TYPE, &amp;pro_e_feature_type );
  C_LOG( &quot; ProElementAlloc &quot; );
  status = ProElementIntegerSet(pro_e_feature_type,PRO_FEAT_CURVE);
<a name="anchor-22"></a>  C_LOG( &quot; ProElementIntegerSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
		pro_e_feature_type );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );

<a name="anchor-23"></a>  /*---------------------------------------------------------------*\
    Populating element PRO_E_CURVE_TYPE
  \*---------------------------------------------------------------*/
  
  C_PRINT( &quot; *** Processing Element PRO_E_CURVE_TYPE *** &quot; );
<a name="anchor-24"></a>  status = ProElementAlloc ( PRO_E_CURVE_TYPE, &amp;pro_e_curve_type );
  C_LOG( &quot; ProElementAlloc &quot; );
  status = ProElementIntegerSet(pro_e_curve_type,PRO_CURVE_TYPE_SKETCHED);
  C_LOG( &quot; ProElementIntegerSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
<a name="anchor-25"></a>		pro_e_curve_type );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );
  
  /*---------------------------------------------------------------*\
    Populating  element PRO_E_STD_SECTION
<a name="anchor-26"></a>  \*---------------------------------------------------------------*/

  C_PRINT( &quot; *** Processing Element PRO_E_STD_SECTION *** &quot; );
  status = ProElementAlloc ( PRO_E_STD_SECTION, &amp;pro_e_std_section );
  C_LOG( &quot; ProElementAlloc&quot; );
<a name="anchor-27"></a>  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
		pro_e_std_section  );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );

  /*---------------------------------------------------------------*\
<a name="anchor-28"></a>    Not required to populate   PRO_E_STD_SEC_METHOD 
  \*---------------------------------------------------------------*/
  
/*
  C_PRINT( &quot; *** Processing Element PRO_E_STD_SEC_METHOD *** &quot; );
<a name="anchor-29"></a>  status = ProElementAlloc ( PRO_E_STD_SEC_METHOD, 
		&amp;pro_e_std_sec_method );
  C_LOG( &quot; ProElementAlloc &quot; );
  value_data.type = PRO_VALUE_TYPE_INT;
  value_data.v.i = PRO_SEC_SKETCH ** 25;
<a name="anchor-30"></a>  status = ProValueAlloc ( &amp;value );
  C_LOG( &quot; ProValueAlloc&quot; );
  status = ProValueDataSet ( value, &amp;value_data );
  C_LOG( &quot; ProValueDataSet&quot; );
  status = ProElementValueSet ( pro_e_std_sec_method, value );
<a name="anchor-31"></a>  C_LOG( &quot; ProElementValueSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_std_section, NULL, 
		pro_e_std_sec_method );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );
  
<a name="anchor-32"></a>*/
  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
  \*---------------------------------------------------------------*/
<a name="anchor-33"></a>  C_PRINT( &quot; *** Processing Element PRO_E_STD_SEC_SETUP_PLANE *** &quot; );
  status = ProElementAlloc ( PRO_E_STD_SEC_SETUP_PLANE, 
		&amp;pro_e_std_sec_setup_plane );
  C_LOG( &quot; ProElementAlloc&quot; );
  status = ProElemtreeElementAdd ( pro_e_std_section, NULL, 
<a name="anchor-34"></a>		pro_e_std_sec_setup_plane  );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );
  
  sketch_refs = ( ProSelection *) calloc ( 2, sizeof ( ProSelection ));

<a name="anchor-35"></a>  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE
  \*---------------------------------------------------------------*/
<a name="anchor-36"></a>  
  C_PRINT( &quot; *** Processing Element PRO_E_STD_SEC_PLANE *** &quot; );
  status = ProMessageDisplay ( message_file, &quot;Select Surface for sketch placement&quot;);
  C_LOG( &quot; ProMessageDisplay&quot;  );
  ProTKPrintf ( &quot;Please select datum,surface,sldface,qltface_ID_5 type of Modelitem\n&quot;);
<a name="anchor-37"></a>  status = ProSelect ( &quot;datum,surface,sldface,qltface&quot;, 1, NULL, NULL, 
		NULL, NULL, &amp;p_select, &amp;n_select );
  C_LOG( &quot; ProSelect&quot; );
  if ( n_select &lt;= 0 ) return -1; 
  else
<a name="anchor-38"></a>    {
      status = ProSelectionCopy( p_select[0], &amp;sketch_refs[0]);
      C_LOG (&quot; ProSelectionCopy &quot;);
    }
  status = ProElementAlloc ( PRO_E_STD_SEC_PLANE, &amp;pro_e_std_sec_plane );
<a name="anchor-39"></a>  C_LOG( &quot; ProElementAlloc &quot; );
  status = ProSelectionToReference( p_select[0],&amp;REPDEP_ref1 );
  status = ProElementReferenceSet(pro_e_std_sec_plane,REPDEP_ref1);
  C_LOG( &quot; ProElementReferenceSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_std_sec_setup_plane, NULL, 
<a name="anchor-40"></a>		pro_e_std_sec_plane );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );
  
  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
<a name="anchor-41"></a>			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE_VIEW_DIR
  \*---------------------------------------------------------------*/
  C_PRINT( &quot; *** Processing Element PRO_E_STD_SEC_PLANE_VIEW_DIR *** &quot; );
  status = ProElementAlloc ( PRO_E_STD_SEC_PLANE_VIEW_DIR, 
<a name="anchor-42"></a>		&amp;pro_e_std_sec_plane_view_dir );
  C_LOG( &quot; ProElementAlloc &quot; );
  status = ProElementIntegerSet(pro_e_std_sec_plane_view_dir,PRO_SEC_VIEW_DIR_SIDE_ONE);
  C_LOG( &quot; ProElementIntegerSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_std_sec_setup_plane, NULL, 
<a name="anchor-43"></a>		pro_e_std_sec_plane_view_dir );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );
  
  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
<a name="anchor-44"></a>			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE_ORIENT_DIR
  \*---------------------------------------------------------------*/
  C_PRINT( &quot; *** Processing Element PRO_E_STD_SEC_PLANE_ORIENT_DIR *** &quot; );
  status = ProElementAlloc ( PRO_E_STD_SEC_PLANE_ORIENT_DIR, 
<a name="anchor-45"></a>		&amp;pro_e_std_sec_plane_orient_dir );
  C_LOG( &quot; ProElementAlloc &quot; );
  status = ProElementIntegerSet(pro_e_std_sec_plane_orient_dir,PRO_SEC_ORIENT_DIR_UP);
  C_LOG( &quot; ProElementIntegerSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_std_sec_setup_plane, NULL, 
<a name="anchor-46"></a>		pro_e_std_sec_plane_orient_dir );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );

  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
<a name="anchor-47"></a>			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE_ORIENT_REF
  \*---------------------------------------------------------------*/
  C_PRINT( &quot; *** Processing Element PRO_E_STD_SEC_PLANE_ORIENT_REF *** &quot; );
  status = ProMessageDisplay ( message_file, 
<a name="anchor-48"></a>		&quot;Select Surface for sketch orientation&quot;);
  C_LOG( &quot; ProMessageDisplay&quot;  );
  ProTKPrintf ( &quot;Select datum,surface,sldface,qltface_ID_5 type of Modelitem\n&quot;);
  status = ProSelect ( &quot;datum,surface,sldface,qltface&quot;, 1, NULL, 
		NULL, NULL, NULL, &amp;p_select, &amp;n_select );
<a name="anchor-49"></a>  C_LOG( &quot; ProSelect&quot; );
  if ( n_select &lt;= 0 ) return -1; 
  else
    {
      status = ProSelectionCopy( p_select[0], &amp;sketch_refs[1]);
<a name="anchor-50"></a>      C_LOG (&quot; ProSelectionCopy &quot;);
    }
  
  status = ProElementAlloc ( PRO_E_STD_SEC_PLANE_ORIENT_REF, 
		&amp;pro_e_std_sec_plane_orient_ref );
<a name="anchor-51"></a>  C_LOG( &quot; ProElementAlloc &quot; );
  status = ProSelectionToReference( p_select[0],&amp;REPDEP_ref2 );
  status = ProElementReferenceSet(pro_e_std_sec_plane_orient_ref,REPDEP_ref2);
  C_LOG( &quot; ProElementReferenceSet&quot; );
  status = ProElemtreeElementAdd ( pro_e_std_sec_setup_plane, NULL, 
<a name="anchor-52"></a>		pro_e_std_sec_plane_orient_ref );
  C_LOG( &quot; ProElemtreeElementAdd&quot; );

  /*---------------------------------------------------------------*\
    Creating incomplete feature in the current model.
<a name="anchor-53"></a>  \*---------------------------------------------------------------*/
  status = ProMdlCurrentGet (&amp;model);
  if ( status != PRO_TK_NO_ERROR ) return ( status );
  status = ProMdlToModelitem( model, &amp;model_item ); 
  status = ProSelectionAlloc (p_comp_path, &amp;model_item,
<a name="anchor-54"></a>			   &amp;model_sel);
  

  status = ProArrayAlloc(1,sizeof(ProFeatureCreateOptions),
    1, (ProArray*)&amp;opts);
<a name="anchor-55"></a>
  opts[0]= PRO_FEAT_CR_INCOMPLETE_FEAT;

  status = ProFeatureWithoptionsCreate (model_sel, pro_e_feature_tree,
    opts, PRO_REGEN_NO_FLAGS, &amp;feature, &amp;errors);
<a name="anchor-56"></a>  C_LOG (&quot; ProFeatureWithoptionsCreate&quot;); 

  status = ProArrayFree((ProArray*)&amp;opts);
  
  /* Using the element tree from created feature */ 
<a name="anchor-57"></a>  status = ProFeatureElemtreeExtract (&amp;feature, NULL, PRO_FEAT_EXTRACT_NO_OPTS, &amp;created_elemtree);
  C_LOG (&quot;ProFeatureElemtreeExtract()&quot;);

  /*---------------------------------------------------------------*\
    Getting the initialized section element from the database.
<a name="anchor-58"></a>  \*---------------------------------------------------------------*/
  /* path to PRO_E_SKETCHER element */ 
  path_items[0].type = PRO_ELEM_PATH_ITEM_TYPE_ID;
  path_items[0].path_item.elem_id = PRO_E_STD_SECTION;
  path_items[1].type = PRO_ELEM_PATH_ITEM_TYPE_ID;
<a name="anchor-59"></a>  path_items[1].path_item.elem_id = PRO_E_SKETCHER;
  status = ProElempathAlloc (&amp;path);
  status = ProElempathDataSet (path, path_items, 2);
  
  status = ProElemtreeElementGet ( created_elemtree, path, &amp;sketch_element);
<a name="anchor-60"></a>  C_LOG (&quot; ProElemtreeElementGet PRO_E_SKETCHER &quot;); 

  status = ProElementSpecialvalueGet(sketch_element, NULL, (ProAppData *) &amp;section);
  C_LOG (&quot; ProElementSpecialvalueGet PRO_E_SKETCHER &quot;);
/*---------------------------------------------------------------*\
<a name="anchor-61"></a>   Creating a 3-D section 
\*---------------------------------------------------------------*/
  
  status = UserSectionBuild ( ( ProSection )(section), 
			   sketch_refs ); 
<a name="anchor-62"></a>  C_LOG (&quot;UserSectionBuild&quot;); 
  
/*---------------------------------------------------------------*\
   Redefining the feature to make it complete.
\*---------------------------------------------------------------*/
<a name="anchor-63"></a>
  status = ProSelectionAsmcomppathGet (model_sel, &amp;comp_path);
  C_LOG (&quot; ProSelectionAsmcomppathGet&quot;); 
  
  status = ProArrayAlloc(1,sizeof(ProFeatureCreateOptions),
<a name="anchor-64"></a>    1, (ProArray*)&amp;opts);

  opts[0]= PRO_FEAT_CR_DEFINE_MISS_ELEMS;

  status = ProFeatureWithoptionsRedefine (&amp;comp_path, &amp;feature, created_elemtree,
<a name="anchor-65"></a>    opts, PRO_REGEN_NO_FLAGS, &amp;errors);
  C_LOG (&quot; ProFeatureWithoptionsRedefine&quot;); 

  status = ProArrayFree((ProArray*)&amp;opts);

<a name="anchor-66"></a>/*---------------------------------------------------------------*\
    Free up the allocated memory.
\*---------------------------------------------------------------*/
  status = ProFeatureElemtreeFree (&amp;feature, created_elemtree ); 
  C_LOG (&quot; ProFeatureElemtreeFree&quot;); 
<a name="anchor-67"></a>  
  status = ProElementFree (&amp;pro_e_feature_tree ); 
  C_LOG (&quot; ProElementFree&quot;); 
  
  return (status);
<a name="anchor-68"></a>}

#undef C_LOG
#undef C_PRINT
</pre>
</body>
</html>
