<html>
<head>
<title>UgSketchedPointCreate.c</title>
</head>
<body bgcolor="#ffffff">
<pre><a name="anchor-0"></a>
/*
	Copyright (c) 2024 PTC Inc. and/or Its Subsidiary Companies. All Rights Reserved.
*/

<a name="anchor-1"></a>

/*---------------------- Pro/Toolkit Includes ------------------------*/
#include &lt;ProToolkit.h>
#include &lt;ProFeature.h>
<a name="anchor-2"></a>#include &lt;ProElemId.h>
#include &lt;ProExtrude.h>
#include &lt;ProModFeat.h>
#include &lt;ProStdSection.h>
#include &lt;ProElement.h>
<a name="anchor-3"></a>#include &lt;ProElempath.h>
#include &lt;ProFeatType.h>
#include &lt;ProFeatForm.h>
#include &lt;ProSelection.h>
#include &lt;ProSection.h>
<a name="anchor-4"></a>#include &lt;TestError.h>
#include &lt;ProMessage.h>
#include &lt;ProTKRunTime.h>
#include &lt;ProUtil.h>
#include &lt;ProDtmCrv.h>
<a name="anchor-5"></a>
#define C_LOG(a) ProTKPrintf (&quot;Status for %s is = %d\n&quot;, a, status); \
                 ERROR_CHECK(a, &quot;UgSktExtrusionCreate.c&quot;, status);

#define C_PRINT(a) ProTKPrintf (&quot;%s\n&quot;, a);
<a name="anchor-6"></a>
static ProFileName message_file; 

/*---------------------- Function Prototypes -------------------------*/
ProError UserSectionPointBuild(ProSection, ProSelection *);
<a name="anchor-7"></a>
/*------------------------- Global Data -----------------------------*/

/*===============================================================*\
FUNCTION : ProDemoSketchedPointCreate
<a name="anchor-8"></a>PURPOSE  : Demonstrates the creation of a Point in a Sketched feature.
\*===============================================================*/
ProError ProDemoSketchedPointCreate(void)
{
  ProReference REPDEP_ref2;
<a name="anchor-9"></a>  ProReference REPDEP_ref1;
  ProErrorlist            errors;
  ProMdl                  model;
  ProModelitem            model_item;
  ProSelection            model_sel;
<a name="anchor-10"></a>  ProFeature              feature;
  ProFeatureCreateOptions *opts = 0;
  ProElempath             path;
  ProElempathItem         path_items[2];
  ProAsmcomppath          comp_path;
<a name="anchor-11"></a>  ProAsmcomppath         *p_comp_path = (ProAsmcomppath *)NULL;
  ProValue                value;
  ProSection              section;

  ProElement sketch_element; 
<a name="anchor-12"></a>  ProElement created_elemtree; 
  
  ProElement pro_e_feature_tree;
  ProElement pro_e_feature_type;
  ProElement pro_e_curve_type;
<a name="anchor-13"></a>  ProElement pro_e_std_feature_name;
  ProElement pro_e_std_section;
  ProElement pro_e_std_sec_setup_plane;
  ProElement pro_e_std_sec_plane;
  ProElement pro_e_std_sec_plane_view_dir;
<a name="anchor-14"></a>  ProElement pro_e_std_sec_plane_orient_dir;
  ProElement pro_e_std_sec_plane_orient_ref;
  
  ProSelection *sketch_refs;

<a name="anchor-15"></a>  ProName        wide_string;
  ProError       status;
  ProValueData   value_data;
  ProSelection  *p_select;
  int            n_select;
<a name="anchor-16"></a>
  ProStringToWstring (message_file, &quot;utilities.txt&quot;); 

  /*---------------------------------------------------------------*\
    Populating root element PRO_E_FEATURE_TREE 
<a name="anchor-17"></a>  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_FEATURE_TREE *** &quot;);
  status = ProElementAlloc (PRO_E_FEATURE_TREE, &amp;pro_e_feature_tree); 
  C_LOG (&quot; ProElementAlloc &quot;);

<a name="anchor-18"></a>  /*---------------------------------------------------------------*\
    Populating element PRO_E_FEATURE_TYPE 
  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_FEATURE_TYPE *** &quot;);
  status = ProElementAlloc (PRO_E_FEATURE_TYPE, &amp;pro_e_feature_type);
<a name="anchor-19"></a>  C_LOG(&quot; ProElementAlloc &quot;);
  status = ProElementIntegerSet(pro_e_feature_type,PRO_FEAT_CURVE);
  C_LOG (&quot; ProElementIntegerSet&quot;);
  status = ProElemtreeElementAdd (pro_e_feature_tree, NULL, pro_e_feature_type);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);
<a name="anchor-20"></a>
  /*---------------------------------------------------------------*\
    Populating element PRO_E_CURVE_TYPE
  \*---------------------------------------------------------------*/

<a name="anchor-21"></a>  C_PRINT (&quot; *** Processing Element PRO_E_CURVE_TYPE *** &quot;);
  status = ProElementAlloc (PRO_E_CURVE_TYPE, &amp;pro_e_curve_type);
  C_LOG (&quot; ProElementAlloc &quot;);
  status = ProElementIntegerSet(pro_e_curve_type,PRO_CURVE_TYPE_SKETCHED);
  C_LOG (&quot; ProElementIntegerSet&quot;);
<a name="anchor-22"></a>  status = ProElemtreeElementAdd (pro_e_feature_tree, NULL, pro_e_curve_type);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);

  /*---------------------------------------------------------------*\
    Populating optional element PRO_E_STD_FEATURE_NAME
<a name="anchor-23"></a>  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_STD_FEATURE_NAME *** &quot;);
  status = ProElementAlloc (PRO_E_STD_FEATURE_NAME, &amp;pro_e_std_feature_name); 
  C_LOG (&quot; ProElementAlloc &quot;);
  ProStringToWstring (wide_string, &quot;MY_PNT1&quot;);
<a name="anchor-24"></a>  status = ProElementWstringSet(pro_e_std_feature_name,wide_string);
  C_LOG (&quot; ProElementWstringSet&quot;);
  status = ProElemtreeElementAdd (pro_e_feature_tree, NULL, pro_e_std_feature_name);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);

<a name="anchor-25"></a>  /*---------------------------------------------------------------*\
    Populating compound element PRO_E_STD_SECTION
  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_STD_SECTION *** &quot;);
  status = ProElementAlloc (PRO_E_STD_SECTION, &amp;pro_e_std_section);
<a name="anchor-26"></a>  C_LOG (&quot; ProElementAlloc&quot;);
  status = ProElemtreeElementAdd (pro_e_feature_tree, NULL, pro_e_std_section);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);

  sketch_refs = (ProSelection *)calloc (2, sizeof (ProSelection));
<a name="anchor-27"></a>
  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
  \*---------------------------------------------------------------*/
<a name="anchor-28"></a>  C_PRINT (&quot; *** Processing Element PRO_E_STD_SEC_SETUP_PLANE *** &quot;);
  status = ProElementAlloc (PRO_E_STD_SEC_SETUP_PLANE, &amp;pro_e_std_sec_setup_plane);
  C_LOG (&quot; ProElementAlloc&quot;);
  status = ProElemtreeElementAdd (pro_e_std_section, NULL, pro_e_std_sec_setup_plane);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);
<a name="anchor-29"></a>
  /*---------------------------------------------------------------*\
    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE
<a name="anchor-30"></a>  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_STD_SEC_PLANE *** &quot;);
  status = ProMessageDisplay (message_file, &quot;Select Surface for sketch placement&quot;);
  C_LOG (&quot; ProMessageDisplay&quot;);
  ProTKPrintf (&quot;Please select datum,surface,sldface,qltface_ID_5 type of Modelitem\n&quot;);
<a name="anchor-31"></a>  status = ProSelect (&quot;datum,surface,sldface,qltface&quot;, 1, NULL, NULL, 
                      NULL, NULL, &amp;p_select, &amp;n_select);
  C_LOG (&quot; ProSelect&quot;);
  if ( n_select &lt;= 0 )
    return -1; 
<a name="anchor-32"></a>  else
  {
    status = ProSelectionCopy (p_select[0], &amp;sketch_refs[0]);
    C_LOG (&quot; ProSelectionCopy &quot;);
  }
<a name="anchor-33"></a>  status = ProElementAlloc (PRO_E_STD_SEC_PLANE, &amp;pro_e_std_sec_plane);
  C_LOG (&quot; ProElementAlloc &quot;);
  status = ProSelectionToReference( p_select[0],&amp;REPDEP_ref1 );
  status = ProElementReferenceSet(pro_e_std_sec_plane,REPDEP_ref1);
  C_LOG (&quot; ProElementReferenceSet&quot;);
<a name="anchor-34"></a>  status = ProElemtreeElementAdd (pro_e_std_sec_setup_plane, NULL, 
                                  pro_e_std_sec_plane);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);

  /*---------------------------------------------------------------*\
<a name="anchor-35"></a>    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE_VIEW_DIR
  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_STD_SEC_PLANE_VIEW_DIR *** &quot;);
<a name="anchor-36"></a>  status = ProElementAlloc (PRO_E_STD_SEC_PLANE_VIEW_DIR, 
                            &amp;pro_e_std_sec_plane_view_dir );
  C_LOG (&quot; ProElementAlloc &quot;);
  status = ProElementIntegerSet(pro_e_std_sec_plane_view_dir,PRO_SEC_VIEW_DIR_SIDE_ONE);
  C_LOG (&quot; ProElementIntegerSet&quot;);
<a name="anchor-37"></a>  status = ProElemtreeElementAdd (pro_e_std_sec_setup_plane, NULL, 
                                  pro_e_std_sec_plane_view_dir);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);

  /*---------------------------------------------------------------*\
<a name="anchor-38"></a>    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE_ORIENT_DIR
  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_STD_SEC_PLANE_ORIENT_DIR *** &quot;);
<a name="anchor-39"></a>  status = ProElementAlloc (PRO_E_STD_SEC_PLANE_ORIENT_DIR, 
                            &amp;pro_e_std_sec_plane_orient_dir);
  C_LOG (&quot; ProElementAlloc &quot;);
  status = ProElementIntegerSet(pro_e_std_sec_plane_orient_dir,PRO_SEC_ORIENT_DIR_UP);
  C_LOG (&quot; ProElementIntegerSet&quot;);
<a name="anchor-40"></a>  status = ProElemtreeElementAdd (pro_e_std_sec_setup_plane, NULL, 
                                  pro_e_std_sec_plane_orient_dir);
  C_LOG (&quot; ProElemtreeElementAdd&quot;);

  /*---------------------------------------------------------------*\
<a name="anchor-41"></a>    Populating element PRO_E_STD_SECTION 
			-> PRO_E_STD_SEC_SETUP_PLANE
			   -> PRO_E_STD_SEC_PLANE_ORIENT_REF
  \*---------------------------------------------------------------*/
  C_PRINT (&quot; *** Processing Element PRO_E_STD_SEC_PLANE_ORIENT_REF *** &quot;);
<a name="anchor-42"></a>  status = ProMessageDisplay (message_file, &quot;Select Surface for sketch orientation&quot;);
  C_LOG (&quot; ProMessageDisplay&quot;);
  ProTKPrintf (&quot;Please select datum,surface,sldface,qltface_ID_5 type of Modelitem\n&quot;);
  status = ProSelect (&quot;datum,surface,sldface,qltface&quot;, 1, NULL, 
                      NULL, NULL, NULL, &amp;p_select, &amp;n_select);
<a name="anchor-43"></a>  C_LOG (&quot; ProSelect&quot;);
  if (n_select &lt;= 0)
    return -1; 
  else
  {
<a name="anchor-44"></a>    status = ProSelectionCopy(p_select[0], &amp;sketch_refs[1]);
    C_LOG (&quot; ProSelectionCopy &quot;);
  }

  status = ProElementAlloc (PRO_E_STD_SEC_PLANE_ORIENT_REF, 
<a name="anchor-45"></a>                            &amp;pro_e_std_sec_plane_orient_ref);
  C_LOG (&quot; ProElementAlloc &quot;);
  status = ProSelectionToReference( p_select[0],&amp;REPDEP_ref2 );
  status = ProElementReferenceSet(pro_e_std_sec_plane_orient_ref,REPDEP_ref2);
  C_LOG (&quot; ProElementReferenceSet&quot;);
<a name="anchor-46"></a>  status = ProElemtreeElementAdd (pro_e_std_sec_setup_plane, NULL, 
                                  pro_e_std_sec_plane_orient_ref);
  C_LOG (&quot; ProElemtreeElementAdd&quot; );

  /*---------------------------------------------------------------*\
<a name="anchor-47"></a>    Creating incomplete feature in the current model.
  \*---------------------------------------------------------------*/
  status = ProMdlCurrentGet (&amp;model);
  if ( status != PRO_TK_NO_ERROR )
    return ( status );
<a name="anchor-48"></a>  status = ProMdlToModelitem (model, &amp;model_item); 
  status = ProSelectionAlloc (p_comp_path, &amp;model_item,
                              &amp;model_sel);
  

<a name="anchor-49"></a>  status = ProArrayAlloc(1,sizeof(ProFeatureCreateOptions),
    1, (ProArray*)&amp;opts);

  opts[0]= PRO_FEAT_CR_INCOMPLETE_FEAT;

<a name="anchor-50"></a>  status = ProFeatureWithoptionsCreate (model_sel, pro_e_feature_tree,
    opts, PRO_REGEN_NO_FLAGS, &amp;feature, &amp;errors);
  C_LOG (&quot; ProFeatureWithoptionsCreate&quot;); 

  status = ProArrayFree((ProArray*)&amp;opts);
<a name="anchor-51"></a>  
  /* Using the element tree from created feature */ 
  status = ProFeatureElemtreeExtract (&amp;feature, NULL, PRO_FEAT_EXTRACT_NO_OPTS,
                                      &amp;created_elemtree);
  C_LOG (&quot;ProFeatureElemtreeExtract()&quot;);
<a name="anchor-52"></a>
  /*---------------------------------------------------------------*\
    Getting the initialized section element from the database.
  \*---------------------------------------------------------------*/
  /* path to PRO_E_SKETCHER element */ 
<a name="anchor-53"></a>  path_items[0].type = PRO_ELEM_PATH_ITEM_TYPE_ID;
  path_items[0].path_item.elem_id = PRO_E_STD_SECTION;
  path_items[1].type = PRO_ELEM_PATH_ITEM_TYPE_ID;
  path_items[1].path_item.elem_id = PRO_E_SKETCHER;
  status = ProElempathAlloc (&amp;path);
<a name="anchor-54"></a>  status = ProElempathDataSet (path, path_items, 2);

  status = ProElemtreeElementGet ( created_elemtree, path, &amp;sketch_element);
  C_LOG (&quot; ProElemtreeElementGet PRO_E_SKETCHER &quot;); 

<a name="anchor-55"></a>
  status = ProElementSpecialvalueGet(sketch_element, NULL, (ProAppData *) &amp;section);
  C_LOG(&quot; ProElementSpecialvalueGet&quot;);
/*---------------------------------------------------------------*\
    Create the 3-D Point section and get the section handle 
<a name="anchor-56"></a>\*---------------------------------------------------------------*/

  status = UserSectionPointBuild ((ProSection)section, sketch_refs); 
  C_LOG (&quot; UserSectionPointBuild&quot;); 

<a name="anchor-57"></a>/*---------------------------------------------------------------*\
   Redefining the feature to make it complete.
\*---------------------------------------------------------------*/

  status = ProSelectionAsmcomppathGet (model_sel, &amp;comp_path);
<a name="anchor-58"></a>  C_LOG (&quot; ProSelectionAsmcomppathGet&quot;); 

  status = ProArrayAlloc(1,sizeof(ProFeatureCreateOptions),
    1, (ProArray*)&amp;opts);

<a name="anchor-59"></a>  opts[0]= PRO_FEAT_CR_DEFINE_MISS_ELEMS;

  status = ProFeatureWithoptionsRedefine (&amp;comp_path, &amp;feature, created_elemtree,
    opts, PRO_REGEN_NO_FLAGS, &amp;errors);
  C_LOG (&quot; ProFeatureWithoptionsRedefine&quot;); 
<a name="anchor-60"></a>
  status = ProArrayFree((ProArray*)&amp;opts);

/*---------------------------------------------------------------*\
    Free up the allocated memory.
<a name="anchor-61"></a>\*---------------------------------------------------------------*/
  status = ProFeatureElemtreeFree (&amp;feature, created_elemtree); 
  C_LOG (&quot; ProFeatureElemtreeFree&quot;); 

  status = ProElementFree (&amp;pro_e_feature_tree); 
<a name="anchor-62"></a>  C_LOG (&quot; ProElementFree&quot;); 

  return (status);
}

<a name="anchor-63"></a>#undef C_LOG
#undef C_PRINT
</pre>
</body>
</html>
