<html>
<head>
<title>UgSmtFlgWallCreate.c</title>
</head>
<body bgcolor="#ffffff">
<pre><a name="anchor-0"></a>
/*
	Copyright (c) 2024 PTC Inc. and/or Its Subsidiary Companies. All Rights Reserved.
*/

<a name="anchor-1"></a>#include &lt;ProToolkit.h>
#include &lt;ProFeature.h>
#include &lt;ProSelbuffer.h>
#include &lt;ProReference.h>
#include &lt;ProCrvcollection.h>
<a name="anchor-2"></a>#include &lt;ProUtil.h>
#include &lt;ProSmtFlangeWall.h>
#include &lt;ProSheetmetal.h>
#include &lt;ProMenuBar.h>
#include &lt;ProPopupmenu.h>
<a name="anchor-3"></a>#include &lt;ProMdl.h>
#include &lt;ProFeatType.h>

  
/*=====================================================================*\
<a name="anchor-4"></a>FUNCTION: UserSmtFlgWallCreate
PURPOSE:  Create sheetmetal flange wall features.
\*=====================================================================*/
int UserSmtFlgWallCreate (ProCollection ref_edge_collection,
			    double bend_radius,
<a name="anchor-5"></a>			    ProSection section) 
{
  ProError status;
  ProElement pro_e_feature_tree;
  ProElement pro_e_feature_type;
<a name="anchor-6"></a>  ProElement pro_e_smt_wall_type;
  ProElement pro_e_std_feature_name;
  ProElement pro_e_smt_flange_type;
  ProElement pro_e_std_curve_collection_appl;
  ProElement pro_e_smt_flange_traj_crv_norm;
<a name="anchor-7"></a>  ProElement pro_e_std_section;
  ProElement pro_e_sketcher;
  ProElement pro_e_smt_wall_sharps_to_bends;
  ProElement pro_e_smt_flange_sec_flip;
  ProElement pro_e_smt_flange_depth;
<a name="anchor-8"></a>  ProElement pro_e_smt_flange_side_1_depth;
  ProElement pro_e_smt_flange_depth_type;
  ProElement pro_e_smt_flange_depth_offset;
  ProElement pro_e_smt_flange_side_2_depth;
  ProElement pro_e_smt_fillets;
<a name="anchor-9"></a>  ProElement pro_e_smt_fillets_use_rad;
  ProElement pro_e_smt_fillets_side;
  ProElement pro_e_smt_fillets_value;
  ProElement pro_e_smt_wall_height;
  ProElement pro_e_smt_wall_height_type;
<a name="anchor-10"></a>  ProElement pro_e_smt_wall_height_value;
  ProElement pro_e_smt_bend_relief;
  ProElement pro_e_smt_bend_relief_side1;
  ProElement pro_e_bend_relief_type;
  ProElement pro_e_bend_relief_width;
<a name="anchor-11"></a>  ProElement pro_e_bend_relief_depth;
  ProElement pro_e_bend_relief_angle;
  ProElement pro_e_smt_bend_relief_side2;
  ProElement pro_e_smt_wall_thickness_flip;
  ProElement pro_e_smt_dev_len_calculation;
<a name="anchor-12"></a>  ProElement pro_e_smt_dev_len_source;
  ProElement pro_e_smt_dev_len_y_factor;
  ProElement pro_e_smt_dev_len_y_factor_value;
  ProElement pro_e_smt_dev_len_y_factor_type;
  ProElement pro_e_smt_dev_len_bend_table;
<a name="anchor-13"></a>  ProMdl model;
  ProModelitem model_item;
  ProFeatureCreateOptions *opts = 0;
  ProSelection model_sel;
  ProFeature feature;
<a name="anchor-14"></a>  ProErrorlist errors;
  ProSelection feat_sel;

/*-----------------------------------------------------------------*\
Processing Element PRO_E_FEATURE_TREE
<a name="anchor-15"></a>\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_FEATURE_TREE, &amp;pro_e_feature_tree ); 
  
/*-----------------------------------------------------------------*\
Processing Element PRO_E_FEATURE_TYPE
<a name="anchor-16"></a>\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_FEATURE_TYPE, &amp;pro_e_feature_type );
  status = ProElementIntegerSet ( pro_e_feature_type, PRO_FEAT_WALL );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_feature_type );
<a name="anchor-17"></a>  
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_WALL_TYPE
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SMT_WALL_TYPE, &amp;pro_e_smt_wall_type );
<a name="anchor-18"></a>  status = ProElementIntegerSet ( pro_e_smt_wall_type, 
				  PRO_SMT_WALL_TYPE_FLANGE );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_smt_wall_type );
  
<a name="anchor-19"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FLANGE_TYPE
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SMT_FLANGE_TYPE, &amp;pro_e_smt_flange_type );
  status = ProElementIntegerSet ( pro_e_smt_flange_type, 
<a name="anchor-20"></a>				  PRO_FLANGE_WALL_TYPE_2D_SWEPT );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_smt_flange_type );
  
/*-----------------------------------------------------------------*\
<a name="anchor-21"></a>Processing Element PRO_E_STD_CURVE_COLLECTION_APPL
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_STD_CURVE_COLLECTION_APPL, 
			     &amp;pro_e_std_curve_collection_appl );
  status = ProElementCollectionSet( pro_e_std_curve_collection_appl, 
<a name="anchor-22"></a>				    ref_edge_collection);
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_std_curve_collection_appl );
  
/*-----------------------------------------------------------------*\
<a name="anchor-23"></a>Processing Element PRO_E_SMT_FLANGE_TRAJ_CRV_NORM
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SMT_FLANGE_TRAJ_CRV_NORM, 
			     &amp;pro_e_smt_flange_traj_crv_norm );
  status = ProElementIntegerSet ( pro_e_smt_flange_traj_crv_norm, 
<a name="anchor-24"></a>				  PRO_FLANGE_TRAJ_NORM_NO_FLIP);
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_smt_flange_traj_crv_norm );
  
/*-----------------------------------------------------------------*\
<a name="anchor-25"></a>Processing Element PRO_E_STD_SECTION
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_STD_SECTION, &amp;pro_e_std_section );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_std_section  );
<a name="anchor-26"></a>
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SKETCHER
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SKETCHER, &amp;pro_e_sketcher );
<a name="anchor-27"></a>  status = ProElementSpecialvalueSet ( pro_e_sketcher, section );
  status = ProElemtreeElementAdd ( pro_e_std_section, NULL, 
				   pro_e_sketcher );
  
/*-----------------------------------------------------------------*\
<a name="anchor-28"></a>Processing Element PRO_E_SMT_WALL_SHARPS_TO_BENDS
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SMT_WALL_SHARPS_TO_BENDS, 
			     &amp;pro_e_smt_wall_sharps_to_bends );
  status = ProElementIntegerSet ( pro_e_smt_wall_sharps_to_bends, 
<a name="anchor-29"></a>				  PRO_B_TRUE );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_smt_wall_sharps_to_bends );
  
/*-----------------------------------------------------------------*\
<a name="anchor-30"></a>Processing Element PRO_E_SMT_FLANGE_SEC_FLIP
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SMT_FLANGE_SEC_FLIP, 
			     &amp;pro_e_smt_flange_sec_flip );
  status = ProElementIntegerSet ( pro_e_smt_flange_sec_flip, 
<a name="anchor-31"></a>				  PRO_B_FALSE );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				   pro_e_smt_flange_sec_flip );

/*-----------------------------------------------------------------*\
<a name="anchor-32"></a>Processing Element PRO_E_SMT_FLANGE_DEPTH
\*-----------------------------------------------------------------*/
  status = ProElementAlloc ( PRO_E_SMT_FLANGE_DEPTH, 
			     &amp;pro_e_smt_flange_depth );
  status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
<a name="anchor-33"></a>				   pro_e_smt_flange_depth  );
  
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FLANGE_SIDE_1_DEPTH
\*-----------------------------------------------------------------*/
<a name="anchor-34"></a>  status = ProElementAlloc ( PRO_E_SMT_FLANGE_SIDE_1_DEPTH, 
			     &amp;pro_e_smt_flange_side_1_depth );
 status = ProElemtreeElementAdd ( pro_e_smt_flange_depth, NULL, 
				  pro_e_smt_flange_side_1_depth  );

<a name="anchor-35"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FLANGE_DEPTH_TYPE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FLANGE_DEPTH_TYPE, 
			    &amp;pro_e_smt_flange_depth_type );
<a name="anchor-36"></a> status = ProElementIntegerSet ( pro_e_smt_flange_depth_type, 
				 PRO_WALL_LEN_TYPE_TO_END);
 status = ProElemtreeElementAdd ( pro_e_smt_flange_side_1_depth, NULL, 
				  pro_e_smt_flange_depth_type );

<a name="anchor-37"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FLANGE_SIDE_2_DEPTH
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FLANGE_SIDE_2_DEPTH, 
			    &amp;pro_e_smt_flange_side_2_depth );
<a name="anchor-38"></a> status = ProElemtreeElementAdd ( pro_e_smt_flange_depth, NULL, 
				  pro_e_smt_flange_side_2_depth  );
 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FLANGE_DEPTH_TYPE
<a name="anchor-39"></a>\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FLANGE_DEPTH_TYPE, 
			    &amp;pro_e_smt_flange_depth_type );
 status = ProElementIntegerSet ( pro_e_smt_flange_depth_type, 
				 PRO_WALL_LEN_TYPE_TO_END );
<a name="anchor-40"></a> status = ProElemtreeElementAdd ( pro_e_smt_flange_side_2_depth, NULL, 
				  pro_e_smt_flange_depth_type );
 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FILLETS
<a name="anchor-41"></a>\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FILLETS, &amp;pro_e_smt_fillets );
 status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				  pro_e_smt_fillets  );
 
<a name="anchor-42"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_FILLETS_USE_RAD
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FILLETS_USE_RAD, 
			    &amp;pro_e_smt_fillets_use_rad );
<a name="anchor-43"></a> status = ProElementIntegerSet ( pro_e_smt_fillets_use_rad, PRO_B_TRUE );
 status = ProElemtreeElementAdd ( pro_e_smt_fillets, NULL, 
				  pro_e_smt_fillets_use_rad );

/*-----------------------------------------------------------------*\
<a name="anchor-44"></a>Processing Element PRO_E_SMT_FILLETS_SIDE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FILLETS_SIDE, 
			    &amp;pro_e_smt_fillets_side );
 status = ProElementIntegerSet ( pro_e_smt_fillets_side, 
<a name="anchor-45"></a>				 PRO_BEND_RAD_INSIDE );
 status = ProElemtreeElementAdd ( pro_e_smt_fillets, NULL, 
				  pro_e_smt_fillets_side );

/*-----------------------------------------------------------------*\
<a name="anchor-46"></a>Processing Element PRO_E_SMT_FILLETS_VALUE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_FILLETS_VALUE, 
			    &amp;pro_e_smt_fillets_value );
 status = ProElementDoubleSet (  pro_e_smt_fillets_value, bend_radius );
<a name="anchor-47"></a> status = ProElemtreeElementAdd ( pro_e_smt_fillets, NULL, 
				  pro_e_smt_fillets_value );

/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_WALL_HEIGHT
<a name="anchor-48"></a>\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_WALL_HEIGHT, &amp;pro_e_smt_wall_height );
 status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				  pro_e_smt_wall_height  );

<a name="anchor-49"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_WALL_HEIGHT_TYPE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_WALL_HEIGHT_TYPE, 
			    &amp;pro_e_smt_wall_height_type );
<a name="anchor-50"></a> status = ProElementIntegerSet ( pro_e_smt_wall_height_type, 
				 PRO_SMT_WALL_HEIGHT_NONE);
 status = ProElemtreeElementAdd ( pro_e_smt_wall_height, NULL, 
				  pro_e_smt_wall_height_type );
 
<a name="anchor-51"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_BEND_RELIEF
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_BEND_RELIEF, &amp;pro_e_smt_bend_relief );
 status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
<a name="anchor-52"></a>				  pro_e_smt_bend_relief  );
 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_BEND_RELIEF_SIDE1
\*-----------------------------------------------------------------*/
<a name="anchor-53"></a> status = ProElementAlloc ( PRO_E_SMT_BEND_RELIEF_SIDE1, 
			    &amp;pro_e_smt_bend_relief_side1 );
 status = ProElemtreeElementAdd ( pro_e_smt_bend_relief, NULL, 
				  pro_e_smt_bend_relief_side1  );
 
<a name="anchor-54"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_BEND_RELIEF_TYPE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_BEND_RELIEF_TYPE, &amp;pro_e_bend_relief_type );
 status = ProElementIntegerSet ( pro_e_bend_relief_type, PRO_BEND_RLF_RIP );
<a name="anchor-55"></a> status = ProElemtreeElementAdd ( pro_e_smt_bend_relief_side1, NULL, 
				  pro_e_bend_relief_type );

/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_BEND_RELIEF_SIDE2
<a name="anchor-56"></a>\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_BEND_RELIEF_SIDE2, 
			    &amp;pro_e_smt_bend_relief_side2 );
 status = ProElemtreeElementAdd ( pro_e_smt_bend_relief, NULL, 
				  pro_e_smt_bend_relief_side2  );
<a name="anchor-57"></a> 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_BEND_RELIEF_TYPE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_BEND_RELIEF_TYPE, 
<a name="anchor-58"></a>			    &amp;pro_e_bend_relief_type );
 status = ProElementIntegerSet ( pro_e_bend_relief_type, PRO_BEND_RLF_RIP );
 status = ProElemtreeElementAdd ( pro_e_smt_bend_relief_side2, NULL, 
				  pro_e_bend_relief_type );
 
<a name="anchor-59"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_WALL_THICKNESS_FLIP
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_WALL_THICKNESS_FLIP, 
			    &amp;pro_e_smt_wall_thickness_flip );
<a name="anchor-60"></a> status = ProElementIntegerSet ( pro_e_smt_wall_thickness_flip, 
				 PRO_B_FALSE );
 status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				  pro_e_smt_wall_thickness_flip );

<a name="anchor-61"></a>/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_DEV_LEN_CALCULATION
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_DEV_LEN_CALCULATION, 
			    &amp;pro_e_smt_dev_len_calculation );
<a name="anchor-62"></a> status = ProElemtreeElementAdd ( pro_e_feature_tree, NULL, 
				  pro_e_smt_dev_len_calculation  );
 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_DEV_LEN_SOURCE
<a name="anchor-63"></a>\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_DEV_LEN_SOURCE, 
			    &amp;pro_e_smt_dev_len_source );
 status = ProElementIntegerSet ( pro_e_smt_dev_len_source, 
				 PRO_DVL_SRC_FEAT_YF_ONLY );
<a name="anchor-64"></a> status = ProElemtreeElementAdd ( pro_e_smt_dev_len_calculation, NULL, 
				  pro_e_smt_dev_len_source );
 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_DEV_LEN_Y_FACTOR
<a name="anchor-65"></a>\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_DEV_LEN_Y_FACTOR, 
			    &amp;pro_e_smt_dev_len_y_factor );
 status = ProElemtreeElementAdd ( pro_e_smt_dev_len_calculation, NULL, 
				  pro_e_smt_dev_len_y_factor  );
<a name="anchor-66"></a> 
/*-----------------------------------------------------------------*\
Processing Element PRO_E_SMT_DEV_LEN_Y_FACTOR_VALUE
\*-----------------------------------------------------------------*/
 status = ProElementAlloc ( PRO_E_SMT_DEV_LEN_Y_FACTOR_VALUE, 
<a name="anchor-67"></a>			    &amp;pro_e_smt_dev_len_y_factor_value );
 status = ProElementDoubleSet (  pro_e_smt_dev_len_y_factor_value, 
				 0.320000 );
 status = ProElemtreeElementAdd ( pro_e_smt_dev_len_y_factor, NULL, 
				  pro_e_smt_dev_len_y_factor_value );
<a name="anchor-68"></a>
/*-----------------------------------------------------------------*\
Create the feature using the element tree
\*-----------------------------------------------------------------*/
 status = ProMdlCurrentGet (&amp;model);
<a name="anchor-69"></a> status = ProMdlToModelitem( model, &amp;model_item );
 status = ProSelectionAlloc (NULL, &amp;model_item, &amp;model_sel);


  status = ProArrayAlloc(1,sizeof(ProFeatureCreateOptions),
<a name="anchor-70"></a>    1, (ProArray*)&amp;opts);

  opts[0]= PRO_FEAT_CR_NO_OPTS;

 status = ProFeatureWithoptionsCreate (model_sel, pro_e_feature_tree,
<a name="anchor-71"></a>    opts, PRO_REGEN_NO_FLAGS, &amp;feature, &amp;errors);

  status = ProArrayFree((ProArray*)&amp;opts);
 if (status == PRO_TK_NO_ERROR)
 {
<a name="anchor-72"></a>	 ProSelectionAlloc (NULL, &amp;feature, &amp;feat_sel);
	 ProSelbufferClear ();
	 ProSelbufferSelectionAdd (feat_sel);
	 ProSelectionFree (&amp;feat_sel);
 }
<a name="anchor-73"></a>
 return (PRO_TK_NO_ERROR);
}


<a name="anchor-74"></a>/*=====================================================================*\
FUNCTION: UserSmtFlgWallCreate_OA_CreateISec
PURPOSE:  Create sheetmetal flange wall features using Object/Action 
          selection and Pro/E's predefined I-section.
\*=====================================================================*/
<a name="anchor-75"></a>int UserSmtFlgWallCreate_OA_CreateISec ()
{
  ProError status;
  ProSelection* sel;
  ProCollection collection;
<a name="anchor-76"></a>  ProCrvcollinstr instr;
  ProReference reference;
  ProPart part;
  ProDimension thickness_dim;
  double thickness;
<a name="anchor-77"></a>  ProSection i_wall_sec;
  ProPath w_mdlpath;
  ProCharPath mdlpath, secpath;
  char* prodir;
  
<a name="anchor-78"></a>/*-----------------------------------------------------------------*\
Extract the current selected edge or edge chain as the wall attachment
\*-----------------------------------------------------------------*/
  status = ProSelbufferSelectionsGet (&amp;sel);

<a name="anchor-79"></a>  status = ProSelectionCollectionGet (sel[0], &amp;collection);

/*-----------------------------------------------------------------*\
If a single edge is selected, allocate the chain as a tangent chain
\*-----------------------------------------------------------------*/
<a name="anchor-80"></a>  if (status != PRO_TK_NO_ERROR)
    {
      status = ProCrvcollectionAlloc ( &amp;collection );
      status = ProCrvcollinstrAlloc ( PRO_CURVCOLL_TAN_INSTR, &amp;instr );
      status = ProSelectionToReference ( sel[0], &amp;reference );
<a name="anchor-81"></a>      status = ProCrvcollinstrReferenceAdd ( instr, reference );
      status = ProCrvcollectionInstructionAdd ( collection, instr );

      ProReferenceFree (reference);
    }
<a name="anchor-82"></a> 
/*-----------------------------------------------------------------*\
Extract the wall thickness to use for the bend radius
\*-----------------------------------------------------------------*/ 
  status = ProMdlCurrentGet ((ProMdl*)&amp;part);
<a name="anchor-83"></a>  status = ProSmtPartThicknessGet(part, &amp;thickness_dim);
  status = ProDimensionValueGet (&amp;thickness_dim, &amp;thickness);

/*-----------------------------------------------------------------*\
Retrieve the Pro/ENGINEER default section for &quot;I&quot; walls
<a name="anchor-84"></a>\*-----------------------------------------------------------------*/ 
  prodir = getenv (&quot;PRO_DIRECTORY&quot;);
  if (prodir == NULL)
	return PRO_TK_INVALID_DIR;

<a name="anchor-85"></a>  ProTKSprintf (secpath, &quot;%s/text/smt/&quot;, prodir);
  ProTKSprintf (mdlpath, &quot;%si_wall.sec&quot;, secpath);
  ProStringToWstring (w_mdlpath, mdlpath);
  status = ProMdlFiletypeLoad  (w_mdlpath,  PRO_MDLFILE_UNUSED, PRO_B_FALSE, 
					   (ProMdl*)&amp;i_wall_sec);
<a name="anchor-86"></a>
/*-----------------------------------------------------------------*\
Create the feature with the extracted information
\*-----------------------------------------------------------------*/
  UserSmtFlgWallCreate (collection, thickness, i_wall_sec);
<a name="anchor-87"></a>
  ProCollectionFree (&amp;collection);

  return (PRO_TK_NO_ERROR);
}
<a name="anchor-88"></a>
/*=====================================================================*\
FUNCTION: UserSmtFlgWallCreate_OA_CreateUserDefSec
PURPOSE:  Create sheetmetal flange wall features using Object/Action 
          selection and a user-selection 2D section.
<a name="anchor-89"></a>\*=====================================================================*/
int UserSmtFlgWallCreate_OA_CreateUserDefSec ()
{
  ProError status;
  ProSelection* sel;
<a name="anchor-90"></a>  ProCollection collection;
  ProCrvcollinstr instr;
  ProReference reference;
  ProPart part;
  ProDimension thickness_dim;
<a name="anchor-91"></a>  double thickness;
  ProSection userdef_sec;
  ProPath w_mdlpath;
  ProCharPath mdlpath, secpath;
  char* prodir;
<a name="anchor-92"></a>  
/*-----------------------------------------------------------------*\
Prompt the user to select a section for the flange wall
\*-----------------------------------------------------------------*/
  status = UserSectionOpen (&amp;userdef_sec);
<a name="anchor-93"></a>  
  if (status != PRO_TK_NO_ERROR)
    return (status);

/*-----------------------------------------------------------------*\
<a name="anchor-94"></a>Extract the current selected edge or edge chain as the wall attachment
\*-----------------------------------------------------------------*/
  status = ProSelbufferSelectionsGet (&amp;sel);

  status = ProSelectionCollectionGet (sel[0], &amp;collection);
<a name="anchor-95"></a>
  if (status != PRO_TK_NO_ERROR)
    {
      status = ProCrvcollectionAlloc ( &amp;collection );
      status = ProCrvcollinstrAlloc ( PRO_CURVCOLL_TAN_INSTR, &amp;instr );
<a name="anchor-96"></a>      status = ProSelectionToReference ( sel[0], &amp;reference );
      status = ProCrvcollinstrReferenceAdd ( instr, reference );
      status = ProCrvcollectionInstructionAdd ( collection, instr );

      ProReferenceFree (reference);
<a name="anchor-97"></a>    }
  
/*-----------------------------------------------------------------*\
Extract the wall thickness to use for the bend radius
\*-----------------------------------------------------------------*/ 
<a name="anchor-98"></a>  status = ProMdlCurrentGet ((ProMdl*)&amp;part);
  status = ProSmtPartThicknessGet(part, &amp;thickness_dim);
  status = ProDimensionValueGet (&amp;thickness_dim, &amp;thickness);

/*-----------------------------------------------------------------*\
<a name="anchor-99"></a>Create the feature with the extracted information
\*-----------------------------------------------------------------*/
  UserSmtFlgWallCreate (collection, thickness, userdef_sec);

  ProMdlErase (userdef_sec);
<a name="anchor-100"></a> 
  ProCollectionFree (&amp;collection);

  return (PRO_TK_NO_ERROR);
}
<a name="anchor-101"></a>
#define OA 1  /* Standard OA in the menu system, typically gray out 
		 the button when not usable*/
#define PM 2 /* OA in a popup menu, typically remove the button when 
	         not usable */
<a name="anchor-102"></a>
/*=====================================================================*\
FUNCTION: UserSmtFlgWallCreate_TestLow
PURPOSE:  Access function for the button for smt flange wall feature creation
\*=====================================================================*/
<a name="anchor-103"></a>static uiCmdAccessState UserSmtFlgWallCreate_TestLow (ProSelection* sels, int mode)
{
  uiCmdAccessState access_result;
  ProBoolean should_free = PRO_B_FALSE;
  ProError status;
<a name="anchor-104"></a>  ProMdl mdl;
  ProMdlType type;
  ProMdlsubtype subtype;
  int size, refs_size;
  ProCollection collection;
<a name="anchor-105"></a>  ProCollectionType coll_type;
  ProCrvcollinstr* instrs;
  int i, j;
  ProCrvcollinstrType instr_type;
  ProReference* refs;
<a name="anchor-106"></a>  ProModelitem item;
  ProBoolean invalid_ref;

/*-----------------------------------------------------------------*\
  Set the default return if the button is unusable.
<a name="anchor-107"></a>\*-----------------------------------------------------------------*/  
  if (mode == OA)
    access_result = ACCESS_UNAVAILABLE;
  else 
    access_result = ACCESS_REMOVE;
<a name="anchor-108"></a>
  status = ProMdlCurrentGet (&amp;mdl);

  if (status != PRO_TK_NO_ERROR)
    return (access_result);
<a name="anchor-109"></a>
  status = ProMdlTypeGet (mdl, &amp;type);

  status = ProMdlSubtypeGet (mdl, &amp;subtype);
  
<a name="anchor-110"></a>  if (type != PRO_MDL_PART || subtype != PROMDLSTYPE_PART_SHEETMETAL)
    return (access_result);

/*-----------------------------------------------------------------*\
  If called without selections, extract the current selections from
<a name="anchor-111"></a>  the buffer.
\*-----------------------------------------------------------------*/ 
  if (sels == NULL)
    {   
      status = ProSelbufferSelectionsGet (&amp;sels);
<a name="anchor-112"></a>      
      if (status != PRO_TK_NO_ERROR)
	return access_result;

      if (sels == NULL)
<a name="anchor-113"></a>	return access_result;

      should_free = PRO_B_TRUE;
    }

<a name="anchor-114"></a>/*-----------------------------------------------------------------*\
  This command allows only one selection.
\*-----------------------------------------------------------------*/   
  status = ProArraySizeGet (sels, &amp;size);
  
<a name="anchor-115"></a>  if (status != PRO_TK_NO_ERROR)
    return access_result;

  if (size == 1)
    {
<a name="anchor-116"></a>/*-----------------------------------------------------------------*\
Extract the crv collection selected by the user
\*-----------------------------------------------------------------*/    
      status = ProSelectionCollectionGet (sels [0], &amp;collection);
      ProTKPrintf (&quot;Status of ProSelectionCollectionGet: %d\n\n&quot;, status);
<a name="anchor-117"></a>
      if (status == PRO_TK_NO_ERROR)
	{
	  status = ProCollectionTypeGet (collection, &amp;coll_type);
	  
<a name="anchor-118"></a>	  if (coll_type == PRO_COLLECTION_CRVCOLL)
	    {
/*-----------------------------------------------------------------*\
Check the instructions assigned to the curve collection.
Exclude this collection if the instruction contains a type not
<a name="anchor-119"></a>supported for this feature
\*-----------------------------------------------------------------*/
	      status = ProCrvcollectionInstructionsGet (collection, &amp;instrs);

	      status = ProArraySizeGet (instrs, &amp;size);
<a name="anchor-120"></a>
	      for (i = 0; i &lt; size; i ++)
		{
		  status = ProCrvcollinstrTypeGet (instrs[i], &amp;instr_type);
		  
<a name="anchor-121"></a>		  if (instr_type != PRO_CURVCOLL_ADD_ONE_INSTR &amp;&amp;
		      instr_type != PRO_CURVCOLL_TAN_INSTR &amp;&amp;
		      instr_type != PRO_CURVCOLL_TRIM_INSTR &amp;&amp;
		      instr_type != PRO_CURVCOLL_START_PNT_INSTR &amp;&amp;
		      instr_type != PRO_CURVCOLL_ADD_TANGENT_INSTR)
<a name="anchor-122"></a>		    break;

/*-----------------------------------------------------------------*\
Check the references to ensure that the reference is an edge 
which borders a sheetmetal face.
<a name="anchor-123"></a>\*-----------------------------------------------------------------*/
		  status = ProCrvcollinstrReferencesGet (instrs[i], &amp;refs);
		  
		  status = ProArraySizeGet (refs, &amp;refs_size);

<a name="anchor-124"></a>		  invalid_ref = PRO_B_FALSE;
		  for (j = 0; j &lt; refs_size; j ++)
		    {
		      ProReferenceTypeGet (refs[j], &amp;item.type);
		      
<a name="anchor-125"></a>		      if (item.type != PRO_EDGE)
			break;
		      
		      ProReferenceOwnerGet (refs[j], &amp;item.owner);
		      ProReferenceIdGet (refs[j], &amp;item.id);
<a name="anchor-126"></a>		      
		      ProReferenceFree (refs[j]);
		      
		      if (!UserEdgeIsSmtFaceEdge (&amp;item))
			invalid_ref = PRO_B_TRUE;
<a name="anchor-127"></a>		    }
		  ProReferencearrayFree (refs);

		  if (invalid_ref)
		    break;
<a name="anchor-128"></a>
/*-----------------------------------------------------------------*\
If all instructions and references passed, the button should be active.
\*-----------------------------------------------------------------*/
		  if (i == size -1)
<a name="anchor-129"></a>		    access_result = ACCESS_AVAILABLE;
		}
	      ProCrvcollinstrArrayFree (instrs);
	    }
	  ProCollectionFree (&amp;collection);
<a name="anchor-130"></a>	}
      else
	{
	  status = ProSelectionModelitemGet (sels [0], &amp;item);

<a name="anchor-131"></a>/*-----------------------------------------------------------------*\
  If the selected type is a single edge, it must border a smt face surface.
\*-----------------------------------------------------------------*/   
	  if (item.type == PRO_EDGE)
	    {
<a name="anchor-132"></a>	      if (UserEdgeIsSmtFaceEdge (&amp;item))
		access_result = ACCESS_AVAILABLE; 
	    }
	}
    }
<a name="anchor-133"></a>
  if (should_free)
    ProSelectionarrayFree (sels);
  
  return access_result;
<a name="anchor-134"></a>}


/*=====================================================================*\
FUNCTION: UserSmtFlgWallCreate_TestMdlTree
<a name="anchor-135"></a>PURPOSE:  Access function for the model tree popup menu button.	
\*=====================================================================*/
uiCmdAccessState UserSmtFlgWallCreate_TestMdlTree (uiCmdAccessMode mode)
{ 
  return UserSmtFlgWallCreate_TestLow (NULL, PM);
<a name="anchor-136"></a>}

/*=====================================================================*\
FUNCTION: UserSmtFlgWallCreate_TestPM
PURPOSE:  Access function for the graphics window popup menu button.	
<a name="anchor-137"></a>\*=====================================================================*/
uiCmdAccessState UserSmtFlgWallCreate_TestPM (uiCmdCmdId id,
				      ProAppData data,
				      ProSelection* sels)
{ 
<a name="anchor-138"></a>  return UserSmtFlgWallCreate_TestLow (sels, PM);
}
</pre>
</body>
</html>
