<!DOCTYPE html
  PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-9">
      <meta name="ch:resourceid" content="Sketched_features_create" scheme="atiChunkerMeta">
      
      
      
      
      
      
      <link href="css/styler.css" rel="stylesheet" type="text/css">
      <title>Element Trees: Sketched Features</title>
   
<SCRIPT LANGUAGE="JAVASCRIPT">
  function findProperNode() { top.frames[0].document.apiwizard.manual("MANSKETCHED_FEATURES_CREATE0", location.hash); }
</SCRIPT>

</head>
   <body onLoad="findProperNode()">
      
         
         <a name="0"> </a><div class=" x-title-65-0 x-title-65-1" combinedFontName="off" id="styler-id1.1.1.54.1" class="ChapterTitle">Element Trees: Sketched Features</div>
         <div class=" x-body-2-0">
            <div class=" x-p-7-0">This <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span>  describes the <span class=" x-ph-2-0" id="Sketched_features_create_ElementTreesSketchedFeatures-03_56_10">Creo TOOLKIT</span> functions that enable you to create and manipulate sketched features.
            </div>
            <div class=" x-p-7-0">Sketched features are features that require one or more sections to completely define the feature, such as extruded and revolved
               protrusions.
            </div>
            <div class=" x-p-7-0">This  <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> outlines the necessary steps to programmatically create sketched features using <span class=" x-ph-2-0" id="Sketched_features_create_ElementTreesSketchedFeatures-03_56_10">Creo TOOLKIT</span>.
            </div>
         </div>
         <div class=" x-topic-4-0 x-topic-4-1 x-topic-4-2" combinedFontName="off" id="Sketched_features_create_Overview-02FBAC05_56_16">
            
            <a name="1"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.3.1" class="Heading1">Overview</div>
            <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="2"></a><span class=" x-indexterm-1-0"></span></div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">The <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> <a href="Features_create.html" class=" x-xref-4-0 x-xref-4-5 x-xref-4-6 x-xref-4-9">Element Trees: Principles of Feature Creation</a> explains how to create a simple feature using the feature element tree, and the documentation in the  <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> on <a href="Sections_create.html" class=" x-xref-4-0 x-xref-4-5 x-xref-4-6 x-xref-4-9">Element Trees: Sections</a> explains how to create a section. This <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> explains how to put these methods together, with a few additional techniques, to create features that contain sketched sections.
               </div>
            </div>
            <div class=" x-topic-11-0 x-topic-11-1" id="Sketched_features_create_ElementTreeForSketchedFeatures-_56_31">
               
               <a name="3"> </a><div class=" x-title-27-0 x-title-27-2" combinedFontName="off" id="styler-id1.1.1.54.3.4.1" class="Heading2">Element Tree for Sketched Features</div>
               <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="4"></a><span class=" x-indexterm-1-0"></span></div>
               <div class=" x-body-3-0">
                  <div class=" x-p-7-0">The element tree of any feature that contains a sketch contains a subtree that identifies the sketch object and describes
                     how it is positioned in the model. As this subtree is the same for every sketched feature, it is documented in its own header
                     file, called <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProStdSection.h</span></span>. The diagram below shows the structure of that subtree.
                  </div>
                  <div class=" x-fig-2-0 x-fig-2-2" id="styler-id1.1.1.54.3.4.3.2">
                     <div class=" x-title-62-0" combinedFontName="off" id="styler-id1.1.1.54.3.4.3.2.1">Element Tree for Sketched Features</div>
                     <div class=" x-image-1-0 x-image-1-1"><img alt="Image" src="graphics/ele_tree_sketched_feature.gif"></div>
                  </div>
                  <div class=" x-p-7-0">The subtree of the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SEC_SETUP_PLANE</span></span> element defines the sketch plane, the location of the sketch plane, the orientation plane and the orientation direction,
                     and the viewing direction. You can use Intent Planes as sketch orientation or placement references.
                  </div>
                  <div class=" x-p-7-0">The element <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SKETCHER</span></span> is of type <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">POINTER</span></span>, and its value is the object <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSection</span></span>, introduced in the documentation in the  <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> on Sections.
                  </div>
                  <div class=" x-p-7-0">The element <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SEC_USE_SKETCH</span></span> refers to any valid selected 'Sketch' (sketched datum curve) suitable to the current Sketch Based Feature. When this element
                     is used, the sketch will be stored in the feature as a reference to the sketch feature, and no internal section, sketch plane
                     or orientation will be required. Using this element in the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span> element tree allows a feature to be created in one step, without creating the feature first as incomplete. 
                  </div>
                  <div class=" x-note-2-0 x-note-2-3">
                     <div class=" x--ufe-note-1-0 x--ufe-note-1-1" combinedFontName="off">Note</div>
                     <div class=" x-p-7-0">The use of internal sections, and the process by which an internal-section based feature is created, remains unchanged in
                        <span class=" x-ph-2-0">Pro/ENGINEER Wildfire 2.0</span>.
                     </div>
                  </div>
                  <div class=" x-p-7-0">The following table shows the sketched features that are supported by <span class=" x-ph-2-0" id="Sketched_features_create_ElementTreeForSketchedFeatures-_56_57">Creo TOOLKIT</span>, the names of the corresponding header files which show their element trees, and the IDs of the elements in each tree which
                     contain the standard sketch subtree as shown in the above figure Element Tree for Sketched Features
                  </div>
                  <div class=" x-table-2-0 x-table-2-3" id="styler-id1.1.1.54.3.4.3.8">
                     <table xmlns="" cellpadding="6.666666666666667" class=" x-tgroup-1-0" frame="box" rules="none" style="border-collapse: collapse; border-width: 1pt; " width="100%">
                        <colgroup>
                           <col>
                           <col>
                           <col>
                        </colgroup>
                        <thead align="left" class=" x-thead-1-0" style="font-weight: bold" valign="top">
                           <tr class=" x-row-2-0">
                              <th class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; " valign="top">
                                 <div class=" x-p-3-0">Feature</div>
                              </th>
                              <th class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; " valign="top">
                                 <div class=" x-p-3-0">Header</div>
                              </th>
                              <th class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; " valign="top">
                                 <div class=" x-p-3-0">Element containing Subtree</div>
                              </th>
                           </tr>
                        </thead>
                        <tbody class=" x-tbody-1-0" valign="top">
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Extrude</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProExtrude.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Revolve</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProRevolve.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Rib</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProRib.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Hole</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProHole.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SKETCHER (2D)</span></span></div>
                                 <div class=" x-p-7-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Fill (Flat datum surface)</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFlatSrf.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Draft</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProDraft.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Sketched datum curve</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProDtmCrv.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Sketched datum point</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProDtmCrv.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span></div>
                              </td>
                           </tr>
                           <tr class=" x-row-2-0">
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0">Simple (constant) sweep</div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSweep.h</span></span></div>
                              </td>
                              <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                                 <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SWEEP_SPINE</span></span></div>
                                 <div class=" x-p-7-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SWEEP_SECTION(2D</span></span><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">)</span></span></div>
                              </td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <div class=" x-topic-8-0 x-topic-8-1 x-topic-8-2" id="Sketched_features_create_CreatingFeaturesContainingSecti48_346">
            
            <a name="5"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.4.1" class="Heading1">Creating Features Containing Sections</div>
            <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="6"></a><span class=" x-indexterm-1-0"></span></div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">The <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> <a href="Features_create.html" class=" x-xref-4-0 x-xref-4-5 x-xref-4-6 x-xref-4-9">Element Trees: Principles of Feature Creation</a> explained that to create a feature from an element tree, you build the tree of elements using <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProElementAlloc()</span></span>, <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProElemtreeElementAdd()</span></span>, and so on, and then call <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureCreate()</span></span> to create the feature using the tree. If the feature is to contain a sketch, the sequence is a little more complex.
               </div>
               <div class=" x-p-7-0">As explained in the documentation in the section  <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> on <a href="Sections_create.html" class=" x-xref-4-0 x-xref-4-5 x-xref-4-6 x-xref-4-9">Element Trees: Sections</a>, a 2D section stored in a model file can be allocated by calling <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSection2dAlloc()</span></span>. Instead, <span class=" x-ph-2-0" id="Sketched_features_create_CreatingFeaturesContainingSecti_56_173"><span xmlns="" profilecode="1">Creo Parametric</span></span> must allocate as part of the initial creation of the sketched feature, a section that will be part of a feature. The allocation
                  is done by calling <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureCreate()</span></span> with an element tree which describes at minimum the feature type and form, in order to create an incomplete feature. In creating
                  the feature, <span class=" x-ph-2-0" id="Sketched_features_create_CreatingFeaturesContainingSecti_56_173"><span xmlns="" profilecode="1">Creo Parametric</span></span> calculates the location and orientation of the section, and allocates the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSection</span></span> object. This section is then retrieved from the value of the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SKETCHER</span></span> element that is found in the element tree extracted from the created feature. Fill the empty section using <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSection</span></span> related functions. 
               </div>
               <div class=" x-p-7-0">After adding the section contents and the remaining elements in the tree, add the new information to the feature using <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureRedefine()</span></span>.
               </div>
            </div>
            <div class=" x-topic-11-0 x-topic-11-1" id="Sketched_features_create_ToCreateSketchedFeaturesElement_56_183">
               
               <a name="7"> </a><div class=" x-title-27-0 x-title-27-2" combinedFontName="off" id="styler-id1.1.1.54.4.4.1" class="Heading2">To Create Sketched Features Element Trees</div>
               <div class=" x-body-3-0">
                  <div class=" x-ol-6-0">
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-11-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0.00em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; ">1.</td>
                              <td><span class=" x-p-4-0">Build an element tree but do not include the element <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SKETCHER</span></span>.</span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-15-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0.00em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; ">2.</td>
                              <td><span class=" x-p-4-0">Call <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureCreate()</span></span> with the option <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_FEAT_CR_INCOMPLETE_FEAT</span></span>, so that the incomplete element tree is accepted.</span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-15-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0.00em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; ">3.</td>
                              <td><span class=" x-p-4-0">Extract the value of the element <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SKETCHER</span></span> created by <span class=" x-ph-2-0" id="Sketched_features_create_ToCreateSketchedFeaturesElement_56_197"><span xmlns="" profilecode="1">Creo Parametric</span></span> from an element tree extracted using <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureElemtreeExtract()</span></span> on the incomplete feature.</span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-15-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0.00em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; ">4.</td>
                              <td><span class=" x-p-4-0">Using that value as the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSection</span></span> object, create the necessary section entities and dimensions, and solve the section.</span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-15-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0.00em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; ">5.</td>
                              <td><span class=" x-p-4-0">Add any other elements not previously added to the tree, such as extrusion depth. The depth elements may also be added before
                                    the creation of incomplete feature (before step 2).</span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-12-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0.00em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; ">6.</td>
                              <td><span class=" x-p-4-0">Call <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureRedefine()</span></span> with the completed element tree.</span></td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <div class=" x-topic-8-0 x-topic-8-1 x-topic-8-2" id="Sketched_features_create_CreatingFeaturesWith2DSections-_56_208">
            
            <a name="8"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.5.1" class="Heading1">Creating Features with 2D Sections </div>
            <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="9"></a><span class=" x-indexterm-1-0"></span></div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">Sketched features using 2D sections do not require references to other geometry in the <span class=" x-ph-2-0" id="Sketched_features_create_CreatingFeaturesWith2DSections-_56_215"><span xmlns="" profilecode="1">Creo Parametric</span></span> model. Some examples of where 2D sections are used are:
               </div>
               <div class=" x-ul-2-0">
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-13-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; ">&#8226;&nbsp;</td>
                           <td><span class=" x-p-4-0">Base features, sometimes called first features. This type of feature must be the first feature created in the model, and be
                                 of type <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_FEAT_FIRST_FEAT</span></span>.</span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-16-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; ">&#8226;&nbsp;</td>
                           <td><span class=" x-p-4-0">Sketched hole features.</span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-14-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; ">&#8226;&nbsp;</td>
                           <td><span class=" x-p-4-0">The <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_SWEEP_SECTION</span></span> section of a simple sweep feature.</span></td>
                        </tr>
                     </tbody>
                  </table>
               </div>
               <div class=" x-p-7-0">To create 2D sketched features, follow the steps outlined in the section <a href="#Sketched_features_create_ToCreateSketchedFeaturesElement_56_183" class=" x-xref-4-0 x-xref-4-5 x-xref-4-6 x-xref-4-9">To Create Sketched Features Element Trees</a>.
               </div>
               <div class=" x-note-2-0 x-note-2-3">
                  <div class=" x--ufe-note-1-0 x--ufe-note-1-1" combinedFontName="off">Note</div>
                  <div class=" x-p-7-0">For 2D sketched features, you need not specify section references or use projected 3D entities. Entities in a 2D section are
                     dimensioned to themselves only. A 2D section does not require any elements in the tree to setup the sketch plane or the orientation
                     of the sketch. Thus, the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SEC_SETUP_PLANE</span></span> subtree is not included.
                  </div>
               </div>
            </div>
         </div>
         <div class=" x-topic-8-0 x-topic-8-1 x-topic-8-2" id="Sketched_features_create_VerifyingSectionShapes-0307219D_56_231">
            
            <a name="10"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.6.1" class="Heading1">Verifying Section Shapes</div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">Function Introduced:</div>
               <div class=" x-ul-2-0">
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-13-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="11"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3693.html">ProSectionShapeGet()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
               </div>
               <div class=" x-p-7-0">Certain features may or may not be able to use a section due to the shape of the section. Different sketched feature tools
                  such as extrude and revolve have different requirements for sections. For example, solid protrusions contain only closed and
                  non-intersecting sections. Solid cuts or datum surfaces have open non-intersecting sections. Fill features must have closed
                  sections.
               </div>
               <div class=" x-p-7-0">After the section is regenerated, <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span> obtains the shape of a given section. This information is used to determine if the section is acceptable for feature creation.
               </div>
               <div class=" x-p-7-0">The section shapes are as follows:</div>
               <div class=" x-table-2-0 x-table-2-3" id="styler-id1.1.1.54.6.2.6">
                  <table xmlns="" cellpadding="6.666666666666667" class=" x-tgroup-1-0" frame="box" rules="none" style="border-collapse: collapse; border-width: 1pt; " width="100%">
                     <colgroup>
                        <col>
                        <col>
                        <col>
                     </colgroup>
                     <thead align="left" class=" x-thead-1-0" style="font-weight: bold" valign="top">
                        <tr class=" x-row-2-0">
                           <th class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; " valign="top">
                              <div class=" x-p-3-0">Constant</div>
                           </th>
                           <th class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; " valign="top">
                              <div class=" x-p-3-0">Function</div>
                           </th>
                           <th class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; " valign="top">
                              <div class=" x-p-3-0">Description</div>
                           </th>
                        </tr>
                     </thead>
                     <tbody class=" x-tbody-1-0" valign="top">
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_EMPTY</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">An empty section</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_POINTS</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains only sketched datum points</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_1_OPEN_LOOP</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains a single open loop (and possibly points)</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_1_CLOSED_LOOP</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains a single closed loop (and possibly points)</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_MIXED_LOOPS</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains at least one open and one closed loop (and possibly points)</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_MULTI_OPEN_LOOPS</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains multiple open loops (and possibly points)</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_MULTI_CLOSED_LOOPS</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains multiple closed loops (and possibly points)</div>
                           </td>
                        </tr>
                        <tr class=" x-row-2-0">
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-codeph-1-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_SECSHAPE_INTERSECTING</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionShapeGet()</span></span></div>
                           </td>
                           <td class="entry-in-tbody" style="border-width: 1pt; border-right-style: solid; border-bottom-style: solid; ">
                              <div class=" x-p-3-0">Section contains loops that intersect each other (and possibly points)</div>
                           </td>
                        </tr>
                     </tbody>
                  </table>
               </div>
               <div class=" x-note-2-0 x-note-2-3">
                  <div class=" x--ufe-note-1-0 x--ufe-note-1-1" combinedFontName="off">Note</div>
                  <div class=" x-p-7-0">Use geometry entities and not construction entities to define section shapes that are then used to create solid or surface
                     geometry. To convert the construction entities to geometry entities, use the function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityConstructionSet()</span></span> with the input argument <span class=" x-parmname-3-0">construction</span> set to <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_B_FALSE</span></span>.
                  </div>
               </div>
            </div>
         </div>
         <div class=" x-topic-8-0 x-topic-8-1 x-topic-8-2" id="Sketched_features_create_CreatingFeaturesWith3DSections-_56_331">
            
            <a name="12"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.7.1" class="Heading1">Creating Features with 3D Sections</div>
            <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="13"></a><span class=" x-indexterm-1-0"></span></div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">A 3D section needs to define its location with respect to the existing geometrical features. The subtree contained in the
                  element <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_STD_SEC_SETUP_PLANE</span></span> defines the location of the sketch planeEdge entities; any other 2D entities in the sketch must be dimensioned to those entities,
                  so that their 3D location is fully defined.
               </div>
            </div>
            <div class=" x-topic-11-0 x-topic-11-1" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_339">
               
               <a name="14"> </a><div class=" x-title-27-0 x-title-27-2" combinedFontName="off" id="styler-id1.1.1.54.7.4.1" class="Heading2">3D Section Location in the Owning Model</div>
               <div class=" x-body-3-0">
                  <div class=" x-p-7-0">Function Introduced:</div>
                  <div class=" x-ul-2-0">
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-13-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; "></td>
                              <td><span class=" x-p-4-0"><a name="15"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3674.html">ProSectionLocationGet()</A></li></span></span></td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
                  <div class=" x-p-7-0">For a 2D section in a feature, <span class=" x-ph-2-0" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_348"><span xmlns="" profilecode="1">Creo Parametric</span></span> decides where the section will be positioned in 3D.
                  </div>
                  <div class=" x-p-7-0">If the section is 3D, the feature tree elements below <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SEC_SETUP_PLANE</span></span> specify the sketch plane, the direction from which it is being viewed, an orientation reference, and a direction which that
                     reference represents (TOP, BOTTOM, LEFT or RIGHT). When you call <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureCreate()</span></span>, this information is used to calculate the 3D plane in which the section lies, and its orientation in that plane.
                  </div>
                  <div class=" x-p-7-0">The position of the section origin in the plane is not implied by the element tree, and cannot be specified by the <span class=" x-ph-2-0" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_354">Creo TOOLKIT</span> application: position is chosen arbitrarily by <span class=" x-ph-2-0" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_348"><span xmlns="" profilecode="1">Creo Parametric</span></span>. This is because the interactive user of <span class=" x-ph-2-0" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_348"><span xmlns="" profilecode="1">Creo Parametric</span></span> never deals in absolute coordinates, and doesn&#8217;t need to specify, or even know, the location of the origin of the section.
                     In <span class=" x-ph-2-0" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_354">Creo TOOLKIT</span> describe all section entities in terms of their coordinate values, so you need to find out where <span class=" x-ph-2-0" id="Sketched_features_create_DSectionLocationInTheOwningMode_56_348"><span xmlns="" profilecode="1">Creo Parametric</span></span> has put the origin of the section. This is the role of the function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionLocationGet()</span></span>.
                  </div>
                  <div class=" x-p-7-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionLocationGet()</span></span> provides the transformation matrix that goes from 2D coordinates within the section to 3D coordinates of the owning part
                     or assembly. This is equivalent to describing the position and orientation of the 2D section coordinate system with respect
                     to the base coordinate system of the 3D model.
                  </div>
                  <div class=" x-p-7-0">So <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionLocationGet()</span></span> can be called in order to calculate where to position new section entities so that they are in the correct 3D position in
                     the part or assembly.
                  </div>
               </div>
            </div>
         </div>
         <div class=" x-topic-8-0 x-topic-8-1 x-topic-8-2" id="Sketched_features_create_ReferenceEntitiesAndUseEdge-030_56_367">
            
            <a name="16"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.8.1" class="Heading1">Reference Entities and Use Edge</div>
            <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="17"></a><span class=" x-indexterm-1-0"></span></div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">Functions introduced:</div>
               <div class=" x-ul-2-0">
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-13-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="18"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3672.html">ProSectionEntityFromProjection()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-16-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="19"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3673.html">ProSectionEntityIsProjection()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-16-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="20"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3685.html">ProSectionEntityUseEdge()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-16-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="21"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3686.html">ProSectionEntityUseEdgeLoop()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-16-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="22"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3687.html">ProSectionEntityUseEdgeChain()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-14-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="23"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3694.html">ProSectionEntityReferenceGet()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
               </div>
               <div class=" x-p-7-0">The previous section explained how to set the correct 3D position of new section entities. You also need to make the entities
                  parametric, that is, to ensure that <span class=" x-ph-2-0" id="Sketched_features_create_ReferenceEntitiesAndUseEdge-030_56_394"><span xmlns="" profilecode="1">Creo Parametric</span></span> knows how to calculate their new positions during regeneration.
               </div>
               <div class=" x-p-7-0">When sketching a section using <span class=" x-ph-2-0" id="Sketched_features_create_ReferenceEntitiesAndUseEdge-030_56_394"><span xmlns="" profilecode="1">Creo Parametric</span></span>, entities are positioned parametrically by dimensioning them or aligning them to items in the 3D model. <span class=" x-ph-2-0" id="Sketched_features_create_ReferenceEntitiesAndUseEdge-030_56_399">Creo TOOLKIT</span> does not allow you to explicitly align section entities, but you can add dimensions which relate section entities to 3D entities
                  in the owning model. You can do this using references. A reference entity represents a position in the section of an item
                  in a 3D model that is used as a dimension reference. The reference entity itself does not give rise to 3D geometry in the
                  owning feature. Reference entities are visible in interactive sketcher operations; they are shown as dashed and are used during
                  autodimensioning and alignment operations.
               </div>
               <div class=" x-p-7-0">In <span class=" x-ph-2-0" id="Sketched_features_create_ReferenceEntitiesAndUseEdge-030_56_399">Creo TOOLKIT</span> reference entities are created using <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityFromProjection()</span></span>. This function takes as input a <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSelection</span></span> describing the 3D model entity being projected, and outputs the integer ID of the resulting known section entity. This ID
                  is used to specify the attachment of a section dimension, as described in the documentation in the section  <span class=" x-ph-2-0"><span xmlns="" profilecode="100000000">section</span></span> <a href="Sections_create.html" class=" x-xref-4-0 x-xref-4-5 x-xref-4-6 x-xref-4-9">Element Trees: Sections</a>. Reference entities are included in the output of <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityIdsGet()</span></span>, but can be distinguished from regular section entities by calling the function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityIsProjection()</span></span>.
               </div>
               <div class=" x-p-7-0">To align a section entity with a 3D model entity, project the 3D entity to create a reference entity, and then either add
                  a dimension between this reference entity and the one to be aligned or use <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionAutodim()</span></span> to do this.
               </div>
               <div class=" x-p-7-0">To create a regular section entity whose geometry is itself an exact projection of a 3D model entity, create it and align
                  it in a single step using the function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseEdge()</span></span>. This function has the same arguments as <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityFromProjection()</span></span>, and it creates a reference entity in the same way, but it requires an additional step of copying the reference entity to
                  a regular entity with the same geometry. It outputs the ID of the regular entity it creates. The ID of the reference entity
                  is always 1 less than the ID of the regular entity.
               </div>
               <div class=" x-p-7-0"><span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseEdge()</span></span> is equivalent to the <span class=" x-ph-2-0" id="Sketched_features_create_ReferenceEntitiesAndUseEdge-030_56_394"><span xmlns="" profilecode="1">Creo Parametric</span></span> sketcher command <span class=" x-uicontrol-4-0" combinedFontName="Sanserif-combined"><span xmlns="" class="cf-Sanserif-combined-Default">Use Edge</span></span>. The functions <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseEdgeLoop()</span></span> and <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseEdgeChain()</span></span> allow you to execute a <span class=" x-uicontrol-4-0" combinedFontName="Sanserif-combined"><span xmlns="" class="cf-Sanserif-combined-Default">Use Edge</span></span> operation on multiple edges simultaneously.
               </div>
               <div class=" x-note-2-0 x-note-2-3">
                  <div class=" x--ufe-note-1-0 x--ufe-note-1-1" combinedFontName="off">Note</div>
                  <div class=" x-p-7-0">If you create the known and projected entities first, you need not call <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionLocationGet()</span></span> as described above; instead you can look at the geometry of the known and projected entities, and then position the new entities
                     relative to the projected entities.
                  </div>
               </div>
               <div class=" x-p-7-0">The function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityReferenceGet()</span></span> provides 3D geometry that is a reference for a projected entity in a given section.
               </div>
            </div>
            <div class=" x-topic-11-0 x-topic-11-1" id="Sketched_features_create_CreatingGeometryByOffsetting-03_56_427">
               
               <a name="24"> </a><div class=" x-title-27-0 x-title-27-2" combinedFontName="off" id="styler-id1.1.1.54.8.4.1" class="Heading2">Creating Geometry by Offsetting</div>
               <div class=" x-body-3-0">
                  <div class=" x-p-7-0">The functions described in this section enable you to create offset entities from edges and 3D curve segments from normal,
                     chain and loop selection.
                  </div>
                  <div class=" x-p-7-0">Functions Introduced:</div>
                  <div class=" x-ul-2-0">
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-13-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; "></td>
                              <td><span class=" x-p-4-0"><a name="25"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3690.html">ProSectionEntityUseOffset()</A></li></span></span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-16-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; "></td>
                              <td><span class=" x-p-4-0"><a name="26"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3691.html">ProSectionEntityUseOffsetChain()</A></li></span></span></td>
                           </tr>
                        </tbody>
                     </table>
                     <table border="0" cellpadding="0" cellspacing="0" class=" x-li-14-0" style="table-layout: fixed; " width="100%">
                        <col style="width: 0em">
                        <col style="width: 18pt">
                        <col>
                        <tbody>
                           <tr valign="baseline">
                              <td align="right"></td>
                              <td align="left" style="word-break: keep-all; "></td>
                              <td><span class=" x-p-4-0"><a name="27"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/3692.html">ProSectionEntityUseOffsetLoop()</A></li></span></span></td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
                  <div class=" x-p-7-0">The function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseOffset()</span></span> creates a sketched entity that is offset at a specified distance from a single edge. This function takes as input a <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSelection</span></span> object describing the 3D model entity. 
                  </div>
                  <div class=" x-p-7-0">The function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseOffsetChain()</span></span> creates sketched entities that are offset from a chain of edges or entities and the function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProSectionEntityUseOffsetLoop()</span></span> creates sketched entities offset from a loop of edges or entities.
                  </div>
                  <div class=" x-p-7-0">The behavior of the functions in this section is similar to the offset operation achieved using <span class=" x-menucascade-1-0"><span class=" x-uicontrol-4-0" combinedFontName="Sanserif-combined"><span xmlns="" class="cf-Sanserif-combined-Default">Sketch</span></span><span class=" x-uicontrol-3-0" combinedFontName="Sanserif-combined"><span class=" x--ufe-menuchoicekeep-1-0"><span xmlns="" class="cf-Sanserif-combined-Default">&nbsp;</span><span style="font-family: 'Arial Unicode MS'; "><span xmlns="" class="cf-Sanserif-combined-Default">&#9654; </span></span></span><span style="font-size: 1pt; "> </span><span xmlns="" class="cf-Sanserif-combined-Default">Offset</span></span></span> in <span class=" x-ph-2-0" id="Sketched_features_create_CreatingGeometryByOffsetting-03_56_452"><span xmlns="" profilecode="1">Creo Parametric</span></span>.
                  </div>
               </div>
            </div>
         </div>
         <div class=" x-topic-8-0 x-topic-8-1 x-topic-8-2" id="Sketched_features_create_ReusingExistingSketches-035823E_56_454">
            
            <a name="28"> </a><div class=" x-title-33-0 x-title-33-2" combinedFontName="off" id="styler-id1.1.1.54.9.1" class="Heading1">Reusing Existing Sketches</div>
            <div class=" x-abstract-1-0"><a xmlns="" class="indexterm" name="29"></a><span class=" x-indexterm-1-0"></span></div>
            <div class=" x-body-3-0">
               <div class=" x-p-7-0">Functions introduced:</div>
               <div class=" x-ul-2-0">
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-13-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="30"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/1485.html">ProFeatureSketchAdd()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
                  <table border="0" cellpadding="0" cellspacing="0" class=" x-li-14-0" style="table-layout: fixed; " width="100%">
                     <col style="width: 0em">
                     <col style="width: 18pt">
                     <col>
                     <tbody>
                        <tr valign="baseline">
                           <td align="right"></td>
                           <td align="left" style="word-break: keep-all; "></td>
                           <td><span class=" x-p-4-0"><a name="31"> </a><span class=" x-apiname-3-0" mcad="FunctionList"><li class="FunctionList"><A HREF="../api/1486.html">ProFeatureSketchedWithOptionsCreate()</A></li></span></span></td>
                        </tr>
                     </tbody>
                  </table>
               </div>
               <div class=" x-p-7-0"><span class=" x-ph-2-0" id="Sketched_features_create_ReusingExistingSketches-035823E_56_469"><span xmlns="" profilecode="1">Creo Parametric</span></span> allows you to copy sections from previously created features into new sketched features.
               </div>
               <div class=" x-p-7-0">The function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureSketchAdd()</span></span> copies the selected section from one feature to another feature.
               </div>
               <div class=" x-p-7-0">The function <span class=" x-cmdname-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">ProFeatureSketchedWithOptionsCreate()</span></span> creates a feature from the element tree, and also copies the sketched sections to the new feature. This reduces the sketched
                  feature creation effort to a single <span class=" x-ph-2-0" id="Sketched_features_create_ReusingExistingSketches-035823E_56_475">Creo TOOLKIT</span> function call. The element tree must contain all of the required elements except the <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">PRO_E_STD_SECTION</span></span> subtree.
               </div>
            </div>
            <div class=" x-topic-11-0 x-topic-11-1" id="Sketched_features_create_Example1CreatingAnExtrudedProtr_56_477">
               
               <a name="32"> </a><div class=" x-title-27-0 x-title-27-2" combinedFontName="off" id="styler-id1.1.1.54.9.4.1" class="Heading2">Example 1: Creating an Extruded Protrusion Base Feature</div>
               <div class=" x-body-3-0">
                  <div class=" x-p-7-0">The sample code in <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">UgSktExtrusionCreate.c</span></span> located at <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">&lt;creo_toolkit_loadpoint&gt;/protk_appls/pt_userguide/ptu_featcreat</span></span> shows the creation of an extruded protrusion as a base feature.
                  </div>
               </div>
            </div>
            <div class=" x-topic-11-0 x-topic-11-1" id="Sketched_features_create_Example2CreatingASketchedDatumC_56_483">
               
               <a name="33"> </a><div class=" x-title-27-0 x-title-27-2" combinedFontName="off" id="styler-id1.1.1.54.9.5.1" class="Heading2">Example 2: Creating a Sketched Datum Curve</div>
               <div class=" x-body-3-0">
                  <div class=" x-p-7-0">The sample code in <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">UgSketchedCurveCreate.c</span></span> located at <span class=" x-codeph-2-0" combinedFontName="Monospace-combined"><span xmlns="" class="cf-Monospace-combined-European_Alphabets">&lt;creo_toolkit_loadpoint&gt;/protk_appls/pt_userguide/ptu_featcreat</span></span> shows the creation of a sketched datum curve using the conventional approach.
                  </div>
               </div>
            </div>
         </div>
      </div>
   </body>
</html>
