<HTML>
    <HEAD>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <TITLE>ProFeatureCreate</TITLE>
    
<SCRIPT LANGUAGE="JAVASCRIPT">
  function findProperNode() { top.frames[0].document.apiwizard.api(11, 1433); }
</SCRIPT>

</HEAD>
    <BODY onLoad="findProperNode()" BGCOLOR="#ffffff">
<h4>Category <a href="category_25.html">Feature element trees</a>, Category <a href="category_29.html">Features</a>, Object <a href="ProFeature.html">ProFeature</a></h4>

        <H2>Function ProFeatureCreate</H2>
        <BR>
        <TABLE BORDER="0">
            <TR>
                <TR VALIGN="top">
                    <TD><b>DEPRECATED: </b></TD><TD> Since Wildfire 5.0</TD>
                </TR>
            </TR>
            <TR>
                <TR>
                    <TD><b>SUPERSEDED BY: </b></TD><TD> <A HREF="1416.html">ProFeatureWithoptionsCreate</A></TD>
                </TR>
            </TR>
            <TR>
                <TD><B><FONT SIZE="5">Description</FONT></B></TD>
            </TR>
            <TR>
                <TD></TD><TD COLSPAN="2">Creates a feature from the element tree.
<p><b> NOTE:
<p></b> This function is deprecated. Use <A HREF="1416.html">ProFeatureWithoptionsCreate</A>() with flags equal to <A HREF="prosolid_h.html#PRO_REGEN_NO_FLAGS">PRO_REGEN_NO_FLAGS</A> for equivalent behavior. Refer to the Creo Parametric Toolkit Release Notes for more information on restrictions of using this function with Multi-CAD models.</TD>
            </TR>
            <TR>
                <TD><B><FONT SIZE="5">Synopsis</FONT></B></TD>
            </TR>
            <TR>
                <TD COLSPAN="3">#include &lt;<A HREF="profeature_h.html">ProFeature.h</A>&gt;</TD>
            </TR>
            <TR VALIGN="top">
                <TD><A HREF="protoolkiterrors_h.html#ProError">ProError</A></TD><TD><B>ProFeatureCreate</B></TD><TD>(</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="proselection_h.html#ProSelection">ProSelection</A> <I>model</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(In)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">A selection object representing the part or assembly on which the feature is being created. The selection object must be constructed using a valid assembly component path to the top level assembly if: <ul> <li>the feature contains external references to geometry located outside of the solid model where it will be constructed. <li>or, the solid model in which the feature will be constructed is a member of the active Creo Parametric assembly. </ul></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="proelement_h.html#ProElement">ProElement</A> <I>elemtree</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(In)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The element tree.</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="profeature_h.html#ProFeatureCreateOptions">ProFeatureCreateOptions</A> <I>options[]</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(In)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">An array of user options.</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD>int <I>num_opts</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(In)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The number of options in the <I>options</I> array.</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="proobjects_h.html#ProFeature">ProFeature</A>* <I>p_feature</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(Out)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The feature handle.</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="proitemerr_h.html#ProErrorlist">ProErrorlist</A>* <I>p_errors</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(Out)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The list of errors.</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD>)</TD>
            </TR>
            <TR>
                <TD><B><FONT SIZE="5">Returns</FONT></B></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">
                    <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_NO_ERROR">PRO_TK_NO_ERROR</A></TD><TD width="30"></TD><TD valign="top">The function successfully created the feature.</TD>
                        </TR>
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_BAD_INPUTS">PRO_TK_BAD_INPUTS</A></TD><TD width="30"></TD><TD valign="top">One or more of the input arguments are invalid.</TD>
                        </TR>
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_GENERAL_ERROR">PRO_TK_GENERAL_ERROR</A></TD><TD width="30"></TD><TD valign="top">The feature was not created. See p_errors for the list of problems.</TD>
                        </TR>
                    </TABLE>
                </TD>
            </TR>
            <TR>
                <TD><B><FONT SIZE="5">See Also</FONT></B></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proanalysis_h.html">ProAnalysis.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proasmcomp_h.html">ProAsmcomp.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="probeltfeat_h.html">ProBeltFeat.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prochamfer_h.html">ProChamfer.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="procontact3dfeat_h.html">ProContact3dFeat.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodamperfeat_h.html">ProDamperFeat.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodesignatedarea_h.html">ProDesignatedArea.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodraft_h.html">ProDraft.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodtmaxis_h.html">ProDtmAxis.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodtmcrv_h.html">ProDtmCrv.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodtmcsys_h.html">ProDtmCsys.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodtmpln_h.html">ProDtmPln.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prodtmpnt_h.html">ProDtmPnt.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proelemid_h.html">ProElemId.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proextrude_h.html">ProExtrude.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="profeatintr_h.html">ProFeatIntr.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="profixture_h.html">ProFixture.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proflatsrf_h.html">ProFlatSrf.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proforeigncurve_h.html">ProForeignCurve.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prohole_h.html">ProHole.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="promfgoper_h.html">ProMfgoper.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="promerge_h.html">ProMerge.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="promirror_h.html">ProMirror.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="promove_h.html">ProMove.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proncseq_h.html">ProNcseq.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proncseqelem_h.html">ProNcseqElem.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="propattern_h.html">ProPattern.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proprocstep_h.html">ProProcstep.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proreplace_h.html">ProReplace.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prorevolve_h.html">ProRevolve.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prorib_h.html">ProRib.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proround_h.html">ProRound.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="proshell_h.html">ProShell.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosmtflangewall_h.html">ProSmtFlangeWall.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosmtflatwall_h.html">ProSmtFlatWall.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosmtform_h.html">ProSmtForm.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosolidify_h.html">ProSolidify.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosmtpunchquilt_h.html">ProSmtPunchQuilt.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prostdsection_h.html">ProStdSection.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosurfreg_h.html">ProSurfReg.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prosweep_h.html">ProSweep.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prothicken_h.html">ProThicken.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="protrim_h.html">ProTrim.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="protoolelem_h.html">ProToolElem.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="provalue_h.html">ProValue.h</A></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2"><A HREF="prowcell_h.html">ProWcell.h</A></TD>
            </TR>
        </TABLE>
    <P>
<p>
<h4>Manual References:</h4>
<p><ol><li><a href="../manual0/ADev_to_TK.html#47">Pro/DEVELOP to Creo Toolkit Function Mapping: Equivalent Pro/DEVELOP Functions</a><li><a href="../manual0/Components_assemble.html#37">Assembly: Assembling Components: Assembling Components by Element Tree</a><li><a href="../manual0/Draft.html#8">Element Trees: Draft Features: Creating a Draft</a><li><a href="../manual0/Draft.html#25">Element Trees: Draft Features: Creating a VPDD</a><li><a href="../manual0/Features_basic.html#50">Core: Features: Feature Inquiry</a><li><a href="../manual0/Features_basic.html#83">Core: Features: Manipulating Features based on Regeneration Flags</a><li><a href="../manual0/Features_create.html#22">Element Trees: Principles of Feature Creation: Feature Creation</a><li><a href="../manual0/Features_create.html#104">Element Trees: Principles of Feature Creation: Calling ProFeatureCreate()</a><li><a href="../manual0/Features_create.html#116">Element Trees: Principles of Feature Creation: Calling ProFeatureCreate()</a><li><a href="../manual0/Features_create.html#117">Element Trees: Principles of Feature Creation: Example of Complete Feature Creation</a><li><a href="../manual0/Features_create.html#128">Element Trees: Principles of Feature Creation: Feature Inquiry</a><li><a href="../manual0/Features_create.html#130">Element Trees: Principles of Feature Creation: Feature Redefine</a><li><a href="../manual0/Features_create.html#136">Element Trees: Principles of Feature Creation: Introduction to Feature Element Trees in XML</a><li><a href="../manual0/Features_create.html#137">Element Trees: Principles of Feature Creation: Validation Using XML Schema</a><li><a href="../manual0/Features_create.html#139">Element Trees: Principles of Feature Creation: Tips for Recycling XML Output of Element Trees</a><li><a href="../manual0/Holes.html#7">Element Trees: Hole: Sketched Hole</a><li><a href="../manual0/Holes.html#28">Element Trees: Hole: Hole Diameter</a><li><a href="../manual0/Holes.html#29">Element Trees: Hole: Order of Element Specification</a><li><a href="../manual0/Menu_features.html#8">Element Trees: Edit Menu Features: Creating a Mirror Feature</a><li><a href="../manual0/Menu_features.html#24">Element Trees: Edit Menu Features: Creating a Move Feature</a><li><a href="../manual0/Menu_features.html#37">Element Trees: Edit Menu Features: Creating a Fill Feature</a><li><a href="../manual0/Menu_features.html#56">Element Trees: Edit Menu Features: Creating a Merge Feature</a><li><a href="../manual0/Menu_features.html#75">Element Trees: Edit Menu Features: Creating a Trim Feature</a><li><a href="../manual0/Menu_features.html#90">Element Trees: Edit Menu Features: Creating a Thicken Feature</a><li><a href="../manual0/Menu_features.html#103">Element Trees: Edit Menu Features: Creating a Solidify Feature</a><li><a href="../manual0/Menu_features.html#117">Element Trees: Edit Menu Features: Creating the Remove Feature</a><li><a href="../manual0/Menu_features.html#131">Element Trees: Edit Menu Features: Creating the Attach Feature</a><li><a href="../manual0/Mfg.html#42">Production Applications: Manufacturing: Creating Manufacturing Objects</a><li><a href="../manual0/Mfg.html#91">Production Applications: Manufacturing: Creating Fixtures</a><li><a href="../manual0/Process_plan.html#18">Production Applications: Process Planning: Creating Process Steps</a><li><a href="../manual0/Round_chamfer.html#7">Element Trees: Round and Chamfer: Creating a Round</a><li><a href="../manual0/Round_chamfer.html#28">Element Trees: Round and Chamfer: Creating a Chamfer</a><li><a href="../manual0/Round_chamfer.html#44">Element Trees: Round and Chamfer: Creating a Corner Chamfer</a><li><a href="../manual0/Sketched_features_create.html#6">Element Trees: Sketched Features: Creating Features Containing Sections</a><li><a href="../manual0/Sketched_features_create.html#7">Element Trees: Sketched Features: To Create Sketched Features Element Trees</a><li><a href="../manual0/Sketched_features_create.html#15">Element Trees: Sketched Features: 3D Section Location in the Owning Model</a><li><a href="../manual0/Surface_replace_tweak.html#5">Element Trees: Replace: The Feature Element Tree</a><li><a href="../manual0/feature_extrude_revolve.html#6">Element Trees: Extrude and Revolve: Conventional Approach</a><li><a href="../manual0/feature_extrude_revolve.html#13">Element Trees: Extrude and Revolve: Example 9: Creating the First Extruded Protrusion Feature by Conventional Approach</a><li><a href="../manual0/feature_extrude_revolve.html#14">Element Trees: Extrude and Revolve: Example 10: Creating the First Thin Revolve Protrusion Feature by Conventional Approach</a><li><a href="../manual0/selobj.html#32">User Interface: Selection: ProSelection Function Examples</a><li><a href="../manual0/sheetmetal.html#34">Production Applications: Sheetmetal: Creating a Flat Wall Feature</a><li><a href="../manual0/sheetmetal.html#47">Production Applications: Sheetmetal: Creating a Flange Wall Feature</a><li><a href="../manual0/sheetmetal.html#60">Production Applications: Sheetmetal: Creating a Extend Wall Feature</a><li><a href="../manual0/sheetmetal.html#68">Production Applications: Sheetmetal: Creating a Split Area Feature</a><li><a href="../manual0/sheetmetal.html#76">Production Applications: Sheetmetal: Creating a Punch or Die Form Feature</a><li><a href="../manual0/sheetmetal.html#84">Production Applications: Sheetmetal: Creating a Quilt Form Feature</a><li><a href="../manual0/sheetmetal.html#92">Production Applications: Sheetmetal: Creating a Flatten Form Feature</a><li><a href="../manual0/sheetmetal.html#106">Production Applications: Sheetmetal: Creating a Rip Feature</a><li><a href="../manual0/shell.html#8">Element Trees: Shell: Creating a Shell Feature</a></ol>
<p>
<p>
<h4>Sample Code References:</h4>
<p><ol><li><a href="../samples/PTAFExampleUtils_c.html#anchor-67">pt_af_examples ( PTAFExampleUtils.c )</a><li><a href="../samples/AutoAxis_c.html#anchor-141">pt_autoaxis ( AutoAxis.c )</a><li><a href="../samples/GearDesign_c.html#anchor-91">pt_geardesign ( GearDesign.c )</a><li><a href="../samples/GearDesign_c.html#anchor-96">pt_geardesign ( GearDesign.c )</a><li><a href="../samples/GearDesign_c.html#anchor-201">pt_geardesign ( GearDesign.c )</a><li><a href="../samples/GearDesignUtils_c.html#anchor-100">pt_geardesign ( GearDesignUtils.c )</a><li><a href="../samples/UgMfgMillSeqCreate_c.html#anchor-85">pt_userguide ( UgMfgMillSeqCreate.c )</a></ol><p>
</BODY>
</HTML>
