<HTML>
    <HEAD>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <TITLE>ProBarewindowMdlnameCreate</TITLE>
    
<SCRIPT LANGUAGE="JAVASCRIPT">
  function findProperNode() { top.frames[0].document.apiwizard.api(11, 257); }
</SCRIPT>

</HEAD>
    <BODY onLoad="findProperNode()" BGCOLOR="#ffffff">
<h4>Category <a href="category_1.html">Windows and views</a>, Object <a href="ProBarewindow.html">ProBarewindow</a></h4>

        <H2>Function ProBarewindowMdlnameCreate</H2>
        <BR>
        <TABLE BORDER="0">
            <TR>
                <TD><B><FONT SIZE="5">Description</FONT></B></TD>
            </TR>
            <TR>
                <TD></TD><TD COLSPAN="2">Retrieves a window and attaches the object to it. If the window is already open with the object attached, the function returns the window identifier. If there is an empty window up, the function attaches the object to it. Otherwise, the function creates a new window and attaches the object to it. The window created doesn't have any toolbars or menus. It can be minimized or closed and it has all the regular mouse-driven view capabilites like zoom, rotation and panning.
<p> NOTE:
<p> This function should be used on model present in the session. <b>Note:</b> In Creo 3 this function does not support names longer than 80 characters. It will return <A HREF="protoolkiterrors_h.html#PRO_TK_BAD_INPUTS">PRO_TK_BAD_INPUTS</A> for longer names. The support for <A HREF="prosizeconst_h.html#ProMdlName">ProMdlName</A> will be added in a future release.</TD>
            </TR>
            <TR>
                <TR>
                    <TD><b>Replacement in Object TOOLKIT: </b></TD><TD><A HREF="../../../otk_cpp_doc/objecttoolkit_Creo/api/t-wfcSession-WSession.html#CreateBarewindow">wfcWSession::CreateBarewindow</A></TD>
                </TR>
            </TR>
            <TR>
                <TD><B><FONT SIZE="5">Synopsis</FONT></B></TD>
            </TR>
            <TR>
                <TD COLSPAN="3">#include &lt;<A HREF="prowindows_h.html">ProWindows.h</A>&gt;</TD>
            </TR>
            <TR VALIGN="top">
                <TD><A HREF="protoolkiterrors_h.html#ProError">ProError</A></TD><TD><B>ProBarewindowMdlnameCreate</B></TD><TD>(</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="prosizeconst_h.html#ProMdlName">ProMdlName</A> <I>object_name</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(In)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The name of the object to be retrieved</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD><A HREF="proobjects_h.html#ProType">ProType</A> <I>object_type</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(In)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The type of the object (<A HREF="proobjects_h.html#PRO_PART">PRO_PART</A>, <A HREF="proobjects_h.html#PRO_ASSEMBLY">PRO_ASSEMBLY</A>, <A HREF="proobjects_h.html#PRO_CATIA_PART">PRO_CATIA_PART</A>, <A HREF="proobjects_h.html#PRO_SW_ASSEM">PRO_SW_ASSEM</A> and so on)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD>int* <I>p_window_id</I></TD><TD></TD>
            </TR>
            <TR>
                <TD></TD><TD colspan="2">/*

(Out)</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">The window identifier in which the object was retrieved</TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">*/</TD>
            </TR>
            <TR VALIGN="top">
                <TD>)</TD>
            </TR>
            <TR>
                <TD><B><FONT SIZE="5">Returns</FONT></B></TD>
            </TR>
            <TR VALIGN="top">
                <TD></TD><TD COLSPAN="2">
                    <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_NO_ERROR">PRO_TK_NO_ERROR</A></TD><TD width="30"></TD><TD valign="top">The function successfully retrieved the window and attached the object to it.</TD>
                        </TR>
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_INVALID_TYPE">PRO_TK_INVALID_TYPE</A></TD><TD width="30"></TD><TD valign="top">You specified an invalid object type.</TD>
                        </TR>
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_BAD_INPUTS">PRO_TK_BAD_INPUTS</A></TD><TD width="30"></TD><TD valign="top">Either you specified an invalid object name, or the window identifier is NULL.</TD>
                        </TR>
                        <TR>
                            <TD valign="top"><A HREF="protoolkiterrors_h.html#PRO_TK_E_NOT_FOUND">PRO_TK_E_NOT_FOUND</A></TD><TD width="30"></TD><TD valign="top">The application is trying to open an embedded model (that is, a model representing a single body of a multi-body foreign object) in a separate window. This operation is not supported.</TD>
                        </TR>
                    </TABLE>
                </TD>
            </TR>
        </TABLE>
    <P>
<p>
<h4>Manual References:</h4>
<p><ol><li><a href="../manual0/THA_Multi_CAD_Assembly.html#10">Working with Multi-CAD Models Using Creo Unite: Working with Basic Graphics</a><li><a href="../manual0/THA_Multi_CAD_Assembly.html#48">Working with Multi-CAD Models Using Creo Unite: Functions that Support Multi-CAD Assemblies</a><li><a href="../manual0/THA_Multi_CAD_Assembly.html#58">Working with Multi-CAD Models Using Creo Unite: Superseded Functions</a><li><a href="../manual0/THA_Multi_CAD_Assembly.html#60">Working with Multi-CAD Models Using Creo Unite: Restrictions on Character Length for Multi-CAD Functions</a></ol>
<p>

</BODY>
</HTML>
